/*
 * This file is generated by jOOQ.
 */
package org.a1cey.bookshelf_pro_plugins.db.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.a1cey.bookshelf_pro_plugins.db.jooq.Keys;
import org.a1cey.bookshelf_pro_plugins.db.jooq.Public;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.BookshelfEntry.BookshelfEntryPath;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records.BookshelfEntryLabelRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BookshelfEntryLabel extends TableImpl<BookshelfEntryLabelRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.bookshelf_entry_label</code>
     */
    public static final BookshelfEntryLabel BOOKSHELF_ENTRY_LABEL = new BookshelfEntryLabel();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BookshelfEntryLabelRecord> getRecordType() {
        return BookshelfEntryLabelRecord.class;
    }

    /**
     * The column <code>public.bookshelf_entry_label.bookshelf_entry_id</code>.
     */
    public final TableField<BookshelfEntryLabelRecord, UUID> BOOKSHELF_ENTRY_ID = createField(DSL.name("bookshelf_entry_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.bookshelf_entry_label.label</code>.
     */
    public final TableField<BookshelfEntryLabelRecord, String> LABEL = createField(DSL.name("label"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private BookshelfEntryLabel(Name alias, Table<BookshelfEntryLabelRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private BookshelfEntryLabel(Name alias, Table<BookshelfEntryLabelRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.bookshelf_entry_label</code> table
     * reference
     */
    public BookshelfEntryLabel(String alias) {
        this(DSL.name(alias), BOOKSHELF_ENTRY_LABEL);
    }

    /**
     * Create an aliased <code>public.bookshelf_entry_label</code> table
     * reference
     */
    public BookshelfEntryLabel(Name alias) {
        this(alias, BOOKSHELF_ENTRY_LABEL);
    }

    /**
     * Create a <code>public.bookshelf_entry_label</code> table reference
     */
    public BookshelfEntryLabel() {
        this(DSL.name("bookshelf_entry_label"), null);
    }

    public <O extends Record> BookshelfEntryLabel(Table<O> path, ForeignKey<O, BookshelfEntryLabelRecord> childPath, InverseForeignKey<O, BookshelfEntryLabelRecord> parentPath) {
        super(path, childPath, parentPath, BOOKSHELF_ENTRY_LABEL);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class BookshelfEntryLabelPath extends BookshelfEntryLabel implements Path<BookshelfEntryLabelRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> BookshelfEntryLabelPath(Table<O> path, ForeignKey<O, BookshelfEntryLabelRecord> childPath, InverseForeignKey<O, BookshelfEntryLabelRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private BookshelfEntryLabelPath(Name alias, Table<BookshelfEntryLabelRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public BookshelfEntryLabelPath as(String alias) {
            return new BookshelfEntryLabelPath(DSL.name(alias), this);
        }

        @Override
        public BookshelfEntryLabelPath as(Name alias) {
            return new BookshelfEntryLabelPath(alias, this);
        }

        @Override
        public BookshelfEntryLabelPath as(Table<?> alias) {
            return new BookshelfEntryLabelPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<BookshelfEntryLabelRecord> getPrimaryKey() {
        return Keys.BOOKSHELF_ENTRY_LABEL_PKEY;
    }

    @Override
    public List<ForeignKey<BookshelfEntryLabelRecord, ?>> getReferences() {
        return Arrays.asList(Keys.BOOKSHELF_ENTRY_LABEL__BOOKSHELF_ENTRY_LABEL_BOOKSHELF_ENTRY_ID_FKEY);
    }

    private transient BookshelfEntryPath _bookshelfEntry;

    /**
     * Get the implicit join path to the <code>public.bookshelf_entry</code>
     * table.
     */
    public BookshelfEntryPath bookshelfEntry() {
        if (_bookshelfEntry == null)
            _bookshelfEntry = new BookshelfEntryPath(this, Keys.BOOKSHELF_ENTRY_LABEL__BOOKSHELF_ENTRY_LABEL_BOOKSHELF_ENTRY_ID_FKEY, null);

        return _bookshelfEntry;
    }

    @Override
    public BookshelfEntryLabel as(String alias) {
        return new BookshelfEntryLabel(DSL.name(alias), this);
    }

    @Override
    public BookshelfEntryLabel as(Name alias) {
        return new BookshelfEntryLabel(alias, this);
    }

    @Override
    public BookshelfEntryLabel as(Table<?> alias) {
        return new BookshelfEntryLabel(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public BookshelfEntryLabel rename(String name) {
        return new BookshelfEntryLabel(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BookshelfEntryLabel rename(Name name) {
        return new BookshelfEntryLabel(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public BookshelfEntryLabel rename(Table<?> name) {
        return new BookshelfEntryLabel(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BookshelfEntryLabel where(Condition condition) {
        return new BookshelfEntryLabel(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BookshelfEntryLabel where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BookshelfEntryLabel where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BookshelfEntryLabel where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BookshelfEntryLabel where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BookshelfEntryLabel where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BookshelfEntryLabel where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BookshelfEntryLabel where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BookshelfEntryLabel whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BookshelfEntryLabel whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
