/*
 * This file is generated by jOOQ.
 */
package org.a1cey.bookshelf_pro_plugins.db.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.a1cey.bookshelf_pro_plugins.db.jooq.Keys;
import org.a1cey.bookshelf_pro_plugins.db.jooq.Public;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.Account.AccountPath;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.BookshelfEntryLabel.BookshelfEntryLabelPath;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.ConsumptionProgress.ConsumptionProgressPath;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.MediaItem.MediaItemPath;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.WatchlistItems.WatchlistItemsPath;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.Watchlists.WatchlistsPath;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records.BookshelfEntryRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BookshelfEntry extends TableImpl<BookshelfEntryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.bookshelf_entry</code>
     */
    public static final BookshelfEntry BOOKSHELF_ENTRY = new BookshelfEntry();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BookshelfEntryRecord> getRecordType() {
        return BookshelfEntryRecord.class;
    }

    /**
     * The column <code>public.bookshelf_entry.id</code>.
     */
    public final TableField<BookshelfEntryRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.bookshelf_entry.media_item_id</code>.
     */
    public final TableField<BookshelfEntryRecord, UUID> MEDIA_ITEM_ID = createField(DSL.name("media_item_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.bookshelf_entry.owner</code>.
     */
    public final TableField<BookshelfEntryRecord, UUID> OWNER = createField(DSL.name("owner"), SQLDataType.UUID.nullable(false), this, "");

    private BookshelfEntry(Name alias, Table<BookshelfEntryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private BookshelfEntry(Name alias, Table<BookshelfEntryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.bookshelf_entry</code> table reference
     */
    public BookshelfEntry(String alias) {
        this(DSL.name(alias), BOOKSHELF_ENTRY);
    }

    /**
     * Create an aliased <code>public.bookshelf_entry</code> table reference
     */
    public BookshelfEntry(Name alias) {
        this(alias, BOOKSHELF_ENTRY);
    }

    /**
     * Create a <code>public.bookshelf_entry</code> table reference
     */
    public BookshelfEntry() {
        this(DSL.name("bookshelf_entry"), null);
    }

    public <O extends Record> BookshelfEntry(Table<O> path, ForeignKey<O, BookshelfEntryRecord> childPath, InverseForeignKey<O, BookshelfEntryRecord> parentPath) {
        super(path, childPath, parentPath, BOOKSHELF_ENTRY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class BookshelfEntryPath extends BookshelfEntry implements Path<BookshelfEntryRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> BookshelfEntryPath(Table<O> path, ForeignKey<O, BookshelfEntryRecord> childPath, InverseForeignKey<O, BookshelfEntryRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private BookshelfEntryPath(Name alias, Table<BookshelfEntryRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public BookshelfEntryPath as(String alias) {
            return new BookshelfEntryPath(DSL.name(alias), this);
        }

        @Override
        public BookshelfEntryPath as(Name alias) {
            return new BookshelfEntryPath(alias, this);
        }

        @Override
        public BookshelfEntryPath as(Table<?> alias) {
            return new BookshelfEntryPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<BookshelfEntryRecord> getPrimaryKey() {
        return Keys.BOOKSHELF_ENTRY_PKEY;
    }

    @Override
    public List<UniqueKey<BookshelfEntryRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.BOOKSHELF_ENTRY_OWNER_MEDIA_ITEM_ID_KEY);
    }

    @Override
    public List<ForeignKey<BookshelfEntryRecord, ?>> getReferences() {
        return Arrays.asList(Keys.BOOKSHELF_ENTRY__BOOKSHELF_ENTRY_MEDIA_ITEM_ID_FKEY, Keys.BOOKSHELF_ENTRY__BOOKSHELF_ENTRY_OWNER_FKEY);
    }

    private transient MediaItemPath _mediaItem;

    /**
     * Get the implicit join path to the <code>public.media_item</code> table.
     */
    public MediaItemPath mediaItem() {
        if (_mediaItem == null)
            _mediaItem = new MediaItemPath(this, Keys.BOOKSHELF_ENTRY__BOOKSHELF_ENTRY_MEDIA_ITEM_ID_FKEY, null);

        return _mediaItem;
    }

    private transient AccountPath _account;

    /**
     * Get the implicit join path to the <code>public.account</code> table.
     */
    public AccountPath account() {
        if (_account == null)
            _account = new AccountPath(this, Keys.BOOKSHELF_ENTRY__BOOKSHELF_ENTRY_OWNER_FKEY, null);

        return _account;
    }

    private transient BookshelfEntryLabelPath _bookshelfEntryLabel;

    /**
     * Get the implicit to-many join path to the
     * <code>public.bookshelf_entry_label</code> table
     */
    public BookshelfEntryLabelPath bookshelfEntryLabel() {
        if (_bookshelfEntryLabel == null)
            _bookshelfEntryLabel = new BookshelfEntryLabelPath(this, null, Keys.BOOKSHELF_ENTRY_LABEL__BOOKSHELF_ENTRY_LABEL_BOOKSHELF_ENTRY_ID_FKEY.getInverseKey());

        return _bookshelfEntryLabel;
    }

    private transient ConsumptionProgressPath _consumptionProgress;

    /**
     * Get the implicit to-many join path to the
     * <code>public.consumption_progress</code> table
     */
    public ConsumptionProgressPath consumptionProgress() {
        if (_consumptionProgress == null)
            _consumptionProgress = new ConsumptionProgressPath(this, null, Keys.CONSUMPTION_PROGRESS__CONSUMPTION_PROGRESS_BOOKSHELF_ENTRY_ID_FKEY.getInverseKey());

        return _consumptionProgress;
    }

    private transient WatchlistItemsPath _watchlistItems;

    /**
     * Get the implicit to-many join path to the
     * <code>public.watchlist_items</code> table
     */
    public WatchlistItemsPath watchlistItems() {
        if (_watchlistItems == null)
            _watchlistItems = new WatchlistItemsPath(this, null, Keys.WATCHLIST_ITEMS__WATCHLIST_ITEMS_BOOKSHELF_ENTRY_ID_FKEY.getInverseKey());

        return _watchlistItems;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.watchlists</code> table
     */
    public WatchlistsPath watchlists() {
        return watchlistItems().watchlists();
    }

    @Override
    public BookshelfEntry as(String alias) {
        return new BookshelfEntry(DSL.name(alias), this);
    }

    @Override
    public BookshelfEntry as(Name alias) {
        return new BookshelfEntry(alias, this);
    }

    @Override
    public BookshelfEntry as(Table<?> alias) {
        return new BookshelfEntry(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public BookshelfEntry rename(String name) {
        return new BookshelfEntry(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BookshelfEntry rename(Name name) {
        return new BookshelfEntry(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public BookshelfEntry rename(Table<?> name) {
        return new BookshelfEntry(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BookshelfEntry where(Condition condition) {
        return new BookshelfEntry(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BookshelfEntry where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BookshelfEntry where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BookshelfEntry where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BookshelfEntry where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BookshelfEntry where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BookshelfEntry where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BookshelfEntry where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BookshelfEntry whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BookshelfEntry whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
