/*
 * This file is generated by jOOQ.
 */
package org.a1cey.bookshelf_pro_plugins.db.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.a1cey.bookshelf_pro_plugins.db.jooq.Keys;
import org.a1cey.bookshelf_pro_plugins.db.jooq.Public;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.BookshelfEntry.BookshelfEntryPath;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records.ConsumptionProgressRecord;
import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ConsumptionProgress extends TableImpl<ConsumptionProgressRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.consumption_progress</code>
     */
    public static final ConsumptionProgress CONSUMPTION_PROGRESS = new ConsumptionProgress();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ConsumptionProgressRecord> getRecordType() {
        return ConsumptionProgressRecord.class;
    }

    /**
     * The column <code>public.consumption_progress.id</code>.
     */
    public final TableField<ConsumptionProgressRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.consumption_progress.bookshelf_entry_id</code>.
     */
    public final TableField<ConsumptionProgressRecord, UUID> BOOKSHELF_ENTRY_ID = createField(DSL.name("bookshelf_entry_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.consumption_progress.state</code>.
     */
    public final TableField<ConsumptionProgressRecord, String> STATE = createField(DSL.name("state"), SQLDataType.VARCHAR(11).nullable(false), this, "");

    /**
     * The column <code>public.consumption_progress.type</code>.
     */
    public final TableField<ConsumptionProgressRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.consumption_progress.current_page</code>.
     */
    public final TableField<ConsumptionProgressRecord, Integer> CURRENT_PAGE = createField(DSL.name("current_page"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.consumption_progress.total_pages</code>.
     */
    public final TableField<ConsumptionProgressRecord, Integer> TOTAL_PAGES = createField(DSL.name("total_pages"), SQLDataType.INTEGER, this, "");

    /**
     * The column
     * <code>public.consumption_progress.current_duration_seconds</code>.
     */
    public final TableField<ConsumptionProgressRecord, Integer> CURRENT_DURATION_SECONDS = createField(DSL.name("current_duration_seconds"), SQLDataType.INTEGER, this, "");

    /**
     * The column
     * <code>public.consumption_progress.total_duration_seconds</code>.
     */
    public final TableField<ConsumptionProgressRecord, Integer> TOTAL_DURATION_SECONDS = createField(DSL.name("total_duration_seconds"), SQLDataType.INTEGER, this, "");

    private ConsumptionProgress(Name alias, Table<ConsumptionProgressRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ConsumptionProgress(Name alias, Table<ConsumptionProgressRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.consumption_progress</code> table
     * reference
     */
    public ConsumptionProgress(String alias) {
        this(DSL.name(alias), CONSUMPTION_PROGRESS);
    }

    /**
     * Create an aliased <code>public.consumption_progress</code> table
     * reference
     */
    public ConsumptionProgress(Name alias) {
        this(alias, CONSUMPTION_PROGRESS);
    }

    /**
     * Create a <code>public.consumption_progress</code> table reference
     */
    public ConsumptionProgress() {
        this(DSL.name("consumption_progress"), null);
    }

    public <O extends Record> ConsumptionProgress(Table<O> path, ForeignKey<O, ConsumptionProgressRecord> childPath, InverseForeignKey<O, ConsumptionProgressRecord> parentPath) {
        super(path, childPath, parentPath, CONSUMPTION_PROGRESS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ConsumptionProgressPath extends ConsumptionProgress implements Path<ConsumptionProgressRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ConsumptionProgressPath(Table<O> path, ForeignKey<O, ConsumptionProgressRecord> childPath, InverseForeignKey<O, ConsumptionProgressRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ConsumptionProgressPath(Name alias, Table<ConsumptionProgressRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ConsumptionProgressPath as(String alias) {
            return new ConsumptionProgressPath(DSL.name(alias), this);
        }

        @Override
        public ConsumptionProgressPath as(Name alias) {
            return new ConsumptionProgressPath(alias, this);
        }

        @Override
        public ConsumptionProgressPath as(Table<?> alias) {
            return new ConsumptionProgressPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<ConsumptionProgressRecord> getPrimaryKey() {
        return Keys.CONSUMPTION_PROGRESS_PKEY;
    }

    @Override
    public List<ForeignKey<ConsumptionProgressRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSUMPTION_PROGRESS__CONSUMPTION_PROGRESS_BOOKSHELF_ENTRY_ID_FKEY);
    }

    private transient BookshelfEntryPath _bookshelfEntry;

    /**
     * Get the implicit join path to the <code>public.bookshelf_entry</code>
     * table.
     */
    public BookshelfEntryPath bookshelfEntry() {
        if (_bookshelfEntry == null)
            _bookshelfEntry = new BookshelfEntryPath(this, Keys.CONSUMPTION_PROGRESS__CONSUMPTION_PROGRESS_BOOKSHELF_ENTRY_ID_FKEY, null);

        return _bookshelfEntry;
    }

    @Override
    public List<Check<ConsumptionProgressRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("consumption_progress_state_check"), "(((state)::text = ANY ((ARRAY['NOT_STARTED'::character varying, 'STARTED'::character varying, 'COMPLETED'::character varying])::text[])))", true),
            Internal.createCheck(this, DSL.name("consumption_progress_type_check"), "(((type)::text = ANY ((ARRAY['BOOK'::character varying, 'MOVIE'::character varying, 'EPISODE'::character varying, 'MUSIC'::character varying])::text[])))", true),
            Internal.createCheck(this, DSL.name("cp_chk_book_progress"), "((((type)::text <> 'BOOK'::text) OR ((current_page IS NOT NULL) AND (total_pages IS NOT NULL) AND (current_page >= 0) AND (current_page <= total_pages) AND (current_duration_seconds IS NULL) AND (total_duration_seconds IS NULL))))", true),
            Internal.createCheck(this, DSL.name("cp_chk_movie_episode_music_progress"), "((((type)::text <> ALL ((ARRAY['MOVIE'::character varying, 'EPISODE'::character varying, 'MUSIC'::character varying])::text[])) OR ((current_duration_seconds IS NOT NULL) AND (total_duration_seconds IS NOT NULL) AND (current_duration_seconds >= 0) AND (current_duration_seconds <= total_duration_seconds) AND (current_page IS NULL) AND (total_pages IS NULL))))", true)
        );
    }

    @Override
    public ConsumptionProgress as(String alias) {
        return new ConsumptionProgress(DSL.name(alias), this);
    }

    @Override
    public ConsumptionProgress as(Name alias) {
        return new ConsumptionProgress(alias, this);
    }

    @Override
    public ConsumptionProgress as(Table<?> alias) {
        return new ConsumptionProgress(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ConsumptionProgress rename(String name) {
        return new ConsumptionProgress(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ConsumptionProgress rename(Name name) {
        return new ConsumptionProgress(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ConsumptionProgress rename(Table<?> name) {
        return new ConsumptionProgress(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ConsumptionProgress where(Condition condition) {
        return new ConsumptionProgress(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ConsumptionProgress where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ConsumptionProgress where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ConsumptionProgress where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ConsumptionProgress where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ConsumptionProgress where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ConsumptionProgress where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ConsumptionProgress where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ConsumptionProgress whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ConsumptionProgress whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
