/*
 * This file is generated by jOOQ.
 */
package org.a1cey.bookshelf_pro_plugins.db.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.a1cey.bookshelf_pro_plugins.db.jooq.Keys;
import org.a1cey.bookshelf_pro_plugins.db.jooq.Public;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.ConsumptionProgress.ConsumptionProgressPath;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.ReviewChange.ReviewChangePath;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records.ConsumptionProgressSnapshotRecord;
import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ConsumptionProgressSnapshot extends TableImpl<ConsumptionProgressSnapshotRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>public.consumption_progress_snapshot</code>
     */
    public static final ConsumptionProgressSnapshot CONSUMPTION_PROGRESS_SNAPSHOT = new ConsumptionProgressSnapshot();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ConsumptionProgressSnapshotRecord> getRecordType() {
        return ConsumptionProgressSnapshotRecord.class;
    }

    /**
     * The column
     * <code>public.consumption_progress_snapshot.consumption_state</code>.
     */
    public final TableField<ConsumptionProgressSnapshotRecord, String> CONSUMPTION_STATE = createField(DSL.name("consumption_state"), SQLDataType.VARCHAR(11).nullable(false), this, "");

    /**
     * The column <code>public.consumption_progress_snapshot.type</code>.
     */
    public final TableField<ConsumptionProgressSnapshotRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.consumption_progress_snapshot.created_at</code>.
     */
    public final TableField<ConsumptionProgressSnapshotRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column
     * <code>public.consumption_progress_snapshot.current_page</code>.
     */
    public final TableField<ConsumptionProgressSnapshotRecord, Integer> CURRENT_PAGE = createField(DSL.name("current_page"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.consumption_progress_snapshot.total_pages</code>.
     */
    public final TableField<ConsumptionProgressSnapshotRecord, Integer> TOTAL_PAGES = createField(DSL.name("total_pages"), SQLDataType.INTEGER, this, "");

    /**
     * The column
     * <code>public.consumption_progress_snapshot.current_duration_seconds</code>.
     */
    public final TableField<ConsumptionProgressSnapshotRecord, Integer> CURRENT_DURATION_SECONDS = createField(DSL.name("current_duration_seconds"), SQLDataType.INTEGER, this, "");

    /**
     * The column
     * <code>public.consumption_progress_snapshot.total_duration_seconds</code>.
     */
    public final TableField<ConsumptionProgressSnapshotRecord, Integer> TOTAL_DURATION_SECONDS = createField(DSL.name("total_duration_seconds"), SQLDataType.INTEGER, this, "");

    /**
     * The column
     * <code>public.consumption_progress_snapshot.consumption_progress_id</code>.
     */
    public final TableField<ConsumptionProgressSnapshotRecord, UUID> CONSUMPTION_PROGRESS_ID = createField(DSL.name("consumption_progress_id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("'00000000-0000-0000-0000-000000000000'::uuid"), SQLDataType.UUID)), this, "");

    private ConsumptionProgressSnapshot(Name alias, Table<ConsumptionProgressSnapshotRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ConsumptionProgressSnapshot(Name alias, Table<ConsumptionProgressSnapshotRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.consumption_progress_snapshot</code> table
     * reference
     */
    public ConsumptionProgressSnapshot(String alias) {
        this(DSL.name(alias), CONSUMPTION_PROGRESS_SNAPSHOT);
    }

    /**
     * Create an aliased <code>public.consumption_progress_snapshot</code> table
     * reference
     */
    public ConsumptionProgressSnapshot(Name alias) {
        this(alias, CONSUMPTION_PROGRESS_SNAPSHOT);
    }

    /**
     * Create a <code>public.consumption_progress_snapshot</code> table
     * reference
     */
    public ConsumptionProgressSnapshot() {
        this(DSL.name("consumption_progress_snapshot"), null);
    }

    public <O extends Record> ConsumptionProgressSnapshot(Table<O> path, ForeignKey<O, ConsumptionProgressSnapshotRecord> childPath, InverseForeignKey<O, ConsumptionProgressSnapshotRecord> parentPath) {
        super(path, childPath, parentPath, CONSUMPTION_PROGRESS_SNAPSHOT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ConsumptionProgressSnapshotPath extends ConsumptionProgressSnapshot implements Path<ConsumptionProgressSnapshotRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ConsumptionProgressSnapshotPath(Table<O> path, ForeignKey<O, ConsumptionProgressSnapshotRecord> childPath, InverseForeignKey<O, ConsumptionProgressSnapshotRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ConsumptionProgressSnapshotPath(Name alias, Table<ConsumptionProgressSnapshotRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ConsumptionProgressSnapshotPath as(String alias) {
            return new ConsumptionProgressSnapshotPath(DSL.name(alias), this);
        }

        @Override
        public ConsumptionProgressSnapshotPath as(Name alias) {
            return new ConsumptionProgressSnapshotPath(alias, this);
        }

        @Override
        public ConsumptionProgressSnapshotPath as(Table<?> alias) {
            return new ConsumptionProgressSnapshotPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<ConsumptionProgressSnapshotRecord> getPrimaryKey() {
        return Keys.CONSUMPTION_PROGRESS_SNAPSHOT_PKEY;
    }

    @Override
    public List<ForeignKey<ConsumptionProgressSnapshotRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSUMPTION_PROGRESS_SNAPSHOT__CONSUMPTION_PROGRESS_SNAPSHOT_CONSUMPTION_PROGRESS_ID_FKEY);
    }

    private transient ConsumptionProgressPath _consumptionProgress;

    /**
     * Get the implicit join path to the
     * <code>public.consumption_progress</code> table.
     */
    public ConsumptionProgressPath consumptionProgress() {
        if (_consumptionProgress == null)
            _consumptionProgress = new ConsumptionProgressPath(this, Keys.CONSUMPTION_PROGRESS_SNAPSHOT__CONSUMPTION_PROGRESS_SNAPSHOT_CONSUMPTION_PROGRESS_ID_FKEY, null);

        return _consumptionProgress;
    }

    private transient ReviewChangePath _reviewChange;

    /**
     * Get the implicit to-many join path to the
     * <code>public.review_change</code> table
     */
    public ReviewChangePath reviewChange() {
        if (_reviewChange == null)
            _reviewChange = new ReviewChangePath(this, null, Keys.REVIEW_CHANGE__REVIEW_CHANGE_CONSUMPTION_PROGRESS_SNAPSHOT_FKEY.getInverseKey());

        return _reviewChange;
    }

    @Override
    public List<Check<ConsumptionProgressSnapshotRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("consumption_progress_snapshot_consumption_state_check"), "(((consumption_state)::text = ANY ((ARRAY['NOT_STARTED'::character varying, 'STARTED'::character varying, 'COMPLETED'::character varying])::text[])))", true),
            Internal.createCheck(this, DSL.name("consumption_progress_snapshot_type_check"), "(((type)::text = ANY ((ARRAY['BOOK'::character varying, 'MOVIE'::character varying, 'EPISODE'::character varying, 'MUSIC'::character varying])::text[])))", true),
            Internal.createCheck(this, DSL.name("cps_chk_book_progress"), "((((type)::text <> 'BOOK'::text) OR ((current_page IS NOT NULL) AND (total_pages IS NOT NULL) AND (current_page >= 0) AND (current_page <= total_pages) AND (current_duration_seconds IS NULL) AND (total_duration_seconds IS NULL))))", true),
            Internal.createCheck(this, DSL.name("cps_chk_movie_episode_music_progress"), "((((type)::text <> ALL ((ARRAY['MOVIE'::character varying, 'EPISODE'::character varying, 'MUSIC'::character varying])::text[])) OR ((current_duration_seconds IS NOT NULL) AND (total_duration_seconds IS NOT NULL) AND (current_duration_seconds >= 0) AND (current_duration_seconds <= total_duration_seconds) AND (current_page IS NULL) AND (total_pages IS NULL))))", true)
        );
    }

    @Override
    public ConsumptionProgressSnapshot as(String alias) {
        return new ConsumptionProgressSnapshot(DSL.name(alias), this);
    }

    @Override
    public ConsumptionProgressSnapshot as(Name alias) {
        return new ConsumptionProgressSnapshot(alias, this);
    }

    @Override
    public ConsumptionProgressSnapshot as(Table<?> alias) {
        return new ConsumptionProgressSnapshot(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ConsumptionProgressSnapshot rename(String name) {
        return new ConsumptionProgressSnapshot(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ConsumptionProgressSnapshot rename(Name name) {
        return new ConsumptionProgressSnapshot(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ConsumptionProgressSnapshot rename(Table<?> name) {
        return new ConsumptionProgressSnapshot(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ConsumptionProgressSnapshot where(Condition condition) {
        return new ConsumptionProgressSnapshot(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ConsumptionProgressSnapshot where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ConsumptionProgressSnapshot where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ConsumptionProgressSnapshot where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ConsumptionProgressSnapshot where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ConsumptionProgressSnapshot where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ConsumptionProgressSnapshot where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ConsumptionProgressSnapshot where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ConsumptionProgressSnapshot whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ConsumptionProgressSnapshot whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
