/*
 * This file is generated by jOOQ.
 */
package org.a1cey.bookshelf_pro_plugins.db.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.a1cey.bookshelf_pro_plugins.db.jooq.Keys;
import org.a1cey.bookshelf_pro_plugins.db.jooq.Public;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.MediaItem.MediaItemPath;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records.MediaItemLanguageRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MediaItemLanguage extends TableImpl<MediaItemLanguageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.media_item_language</code>
     */
    public static final MediaItemLanguage MEDIA_ITEM_LANGUAGE = new MediaItemLanguage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MediaItemLanguageRecord> getRecordType() {
        return MediaItemLanguageRecord.class;
    }

    /**
     * The column <code>public.media_item_language.media_item_id</code>.
     */
    public final TableField<MediaItemLanguageRecord, UUID> MEDIA_ITEM_ID = createField(DSL.name("media_item_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.media_item_language.iso_code</code>.
     */
    public final TableField<MediaItemLanguageRecord, String> ISO_CODE = createField(DSL.name("iso_code"), SQLDataType.VARCHAR(3).nullable(false), this, "");

    private MediaItemLanguage(Name alias, Table<MediaItemLanguageRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MediaItemLanguage(Name alias, Table<MediaItemLanguageRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.media_item_language</code> table reference
     */
    public MediaItemLanguage(String alias) {
        this(DSL.name(alias), MEDIA_ITEM_LANGUAGE);
    }

    /**
     * Create an aliased <code>public.media_item_language</code> table reference
     */
    public MediaItemLanguage(Name alias) {
        this(alias, MEDIA_ITEM_LANGUAGE);
    }

    /**
     * Create a <code>public.media_item_language</code> table reference
     */
    public MediaItemLanguage() {
        this(DSL.name("media_item_language"), null);
    }

    public <O extends Record> MediaItemLanguage(Table<O> path, ForeignKey<O, MediaItemLanguageRecord> childPath, InverseForeignKey<O, MediaItemLanguageRecord> parentPath) {
        super(path, childPath, parentPath, MEDIA_ITEM_LANGUAGE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class MediaItemLanguagePath extends MediaItemLanguage implements Path<MediaItemLanguageRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MediaItemLanguagePath(Table<O> path, ForeignKey<O, MediaItemLanguageRecord> childPath, InverseForeignKey<O, MediaItemLanguageRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MediaItemLanguagePath(Name alias, Table<MediaItemLanguageRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MediaItemLanguagePath as(String alias) {
            return new MediaItemLanguagePath(DSL.name(alias), this);
        }

        @Override
        public MediaItemLanguagePath as(Name alias) {
            return new MediaItemLanguagePath(alias, this);
        }

        @Override
        public MediaItemLanguagePath as(Table<?> alias) {
            return new MediaItemLanguagePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<MediaItemLanguageRecord> getPrimaryKey() {
        return Keys.MEDIA_ITEM_LANGUAGE_PKEY;
    }

    @Override
    public List<ForeignKey<MediaItemLanguageRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MEDIA_ITEM_LANGUAGE__MEDIA_ITEM_LANGUAGE_MEDIA_ITEM_ID_FKEY);
    }

    private transient MediaItemPath _mediaItem;

    /**
     * Get the implicit join path to the <code>public.media_item</code> table.
     */
    public MediaItemPath mediaItem() {
        if (_mediaItem == null)
            _mediaItem = new MediaItemPath(this, Keys.MEDIA_ITEM_LANGUAGE__MEDIA_ITEM_LANGUAGE_MEDIA_ITEM_ID_FKEY, null);

        return _mediaItem;
    }

    @Override
    public MediaItemLanguage as(String alias) {
        return new MediaItemLanguage(DSL.name(alias), this);
    }

    @Override
    public MediaItemLanguage as(Name alias) {
        return new MediaItemLanguage(alias, this);
    }

    @Override
    public MediaItemLanguage as(Table<?> alias) {
        return new MediaItemLanguage(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaItemLanguage rename(String name) {
        return new MediaItemLanguage(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaItemLanguage rename(Name name) {
        return new MediaItemLanguage(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaItemLanguage rename(Table<?> name) {
        return new MediaItemLanguage(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaItemLanguage where(Condition condition) {
        return new MediaItemLanguage(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaItemLanguage where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaItemLanguage where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaItemLanguage where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaItemLanguage where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaItemLanguage where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaItemLanguage where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaItemLanguage where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaItemLanguage whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaItemLanguage whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
