/*
 * This file is generated by jOOQ.
 */
package org.a1cey.bookshelf_pro_plugins.db.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.a1cey.bookshelf_pro_plugins.db.jooq.Keys;
import org.a1cey.bookshelf_pro_plugins.db.jooq.Public;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.Account.AccountPath;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.Book.BookPath;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.BookshelfEntry.BookshelfEntryPath;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.MediaItemLanguage.MediaItemLanguagePath;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.Movie.MoviePath;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.Review.ReviewPath;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records.MediaItemRecord;
import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MediaItem extends TableImpl<MediaItemRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.media_item</code>
     */
    public static final MediaItem MEDIA_ITEM = new MediaItem();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MediaItemRecord> getRecordType() {
        return MediaItemRecord.class;
    }

    /**
     * The column <code>public.media_item.id</code>.
     */
    public final TableField<MediaItemRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.media_item.type</code>.
     */
    public final TableField<MediaItemRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.media_item.title</code>.
     */
    public final TableField<MediaItemRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.media_item.subtitle</code>.
     */
    public final TableField<MediaItemRecord, String> SUBTITLE = createField(DSL.name("subtitle"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.media_item.description</code>.
     */
    public final TableField<MediaItemRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.media_item.cover_image_url</code>.
     */
    public final TableField<MediaItemRecord, String> COVER_IMAGE_URL = createField(DSL.name("cover_image_url"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.media_item.owner_id</code>.
     */
    public final TableField<MediaItemRecord, UUID> OWNER_ID = createField(DSL.name("owner_id"), SQLDataType.UUID.nullable(false), this, "");

    private MediaItem(Name alias, Table<MediaItemRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MediaItem(Name alias, Table<MediaItemRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.media_item</code> table reference
     */
    public MediaItem(String alias) {
        this(DSL.name(alias), MEDIA_ITEM);
    }

    /**
     * Create an aliased <code>public.media_item</code> table reference
     */
    public MediaItem(Name alias) {
        this(alias, MEDIA_ITEM);
    }

    /**
     * Create a <code>public.media_item</code> table reference
     */
    public MediaItem() {
        this(DSL.name("media_item"), null);
    }

    public <O extends Record> MediaItem(Table<O> path, ForeignKey<O, MediaItemRecord> childPath, InverseForeignKey<O, MediaItemRecord> parentPath) {
        super(path, childPath, parentPath, MEDIA_ITEM);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class MediaItemPath extends MediaItem implements Path<MediaItemRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MediaItemPath(Table<O> path, ForeignKey<O, MediaItemRecord> childPath, InverseForeignKey<O, MediaItemRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MediaItemPath(Name alias, Table<MediaItemRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MediaItemPath as(String alias) {
            return new MediaItemPath(DSL.name(alias), this);
        }

        @Override
        public MediaItemPath as(Name alias) {
            return new MediaItemPath(alias, this);
        }

        @Override
        public MediaItemPath as(Table<?> alias) {
            return new MediaItemPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<MediaItemRecord> getPrimaryKey() {
        return Keys.MEDIA_ITEM_PKEY;
    }

    @Override
    public List<ForeignKey<MediaItemRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MEDIA_ITEM__MEDIA_ITEM_OWNER_ID_FKEY);
    }

    private transient AccountPath _account;

    /**
     * Get the implicit join path to the <code>public.account</code> table.
     */
    public AccountPath account() {
        if (_account == null)
            _account = new AccountPath(this, Keys.MEDIA_ITEM__MEDIA_ITEM_OWNER_ID_FKEY, null);

        return _account;
    }

    private transient BookPath _book;

    /**
     * Get the implicit to-many join path to the <code>public.book</code> table
     */
    public BookPath book() {
        if (_book == null)
            _book = new BookPath(this, null, Keys.BOOK__BOOK_ID_FKEY.getInverseKey());

        return _book;
    }

    private transient BookshelfEntryPath _bookshelfEntry;

    /**
     * Get the implicit to-many join path to the
     * <code>public.bookshelf_entry</code> table
     */
    public BookshelfEntryPath bookshelfEntry() {
        if (_bookshelfEntry == null)
            _bookshelfEntry = new BookshelfEntryPath(this, null, Keys.BOOKSHELF_ENTRY__BOOKSHELF_ENTRY_MEDIA_ITEM_ID_FKEY.getInverseKey());

        return _bookshelfEntry;
    }

    private transient MediaItemLanguagePath _mediaItemLanguage;

    /**
     * Get the implicit to-many join path to the
     * <code>public.media_item_language</code> table
     */
    public MediaItemLanguagePath mediaItemLanguage() {
        if (_mediaItemLanguage == null)
            _mediaItemLanguage = new MediaItemLanguagePath(this, null, Keys.MEDIA_ITEM_LANGUAGE__MEDIA_ITEM_LANGUAGE_MEDIA_ITEM_ID_FKEY.getInverseKey());

        return _mediaItemLanguage;
    }

    private transient MoviePath _movie;

    /**
     * Get the implicit to-many join path to the <code>public.movie</code> table
     */
    public MoviePath movie() {
        if (_movie == null)
            _movie = new MoviePath(this, null, Keys.MOVIE__MOVIE_ID_FKEY.getInverseKey());

        return _movie;
    }

    private transient ReviewPath _review;

    /**
     * Get the implicit to-many join path to the <code>public.review</code>
     * table
     */
    public ReviewPath review() {
        if (_review == null)
            _review = new ReviewPath(this, null, Keys.REVIEW__REVIEW_MEDIA_ITEM_ID_FKEY.getInverseKey());

        return _review;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.account</code> table, via the
     * <code>bookshelf_entry_owner_fkey</code> key
     */
    public AccountPath bookshelfEntryOwnerFkey() {
        return bookshelfEntry().account();
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.account</code> table, via the <code>review_owner_fkey</code>
     * key
     */
    public AccountPath reviewOwnerFkey() {
        return review().account();
    }

    @Override
    public List<Check<MediaItemRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("media_item_type_check"), "(((type)::text = ANY ((ARRAY['BOOK'::character varying, 'MOVIE'::character varying, 'SERIES'::character varying, 'MUSIC'::character varying])::text[])))", true)
        );
    }

    @Override
    public MediaItem as(String alias) {
        return new MediaItem(DSL.name(alias), this);
    }

    @Override
    public MediaItem as(Name alias) {
        return new MediaItem(alias, this);
    }

    @Override
    public MediaItem as(Table<?> alias) {
        return new MediaItem(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaItem rename(String name) {
        return new MediaItem(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaItem rename(Name name) {
        return new MediaItem(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaItem rename(Table<?> name) {
        return new MediaItem(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaItem where(Condition condition) {
        return new MediaItem(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaItem where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaItem where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaItem where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaItem where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaItem where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaItem where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaItem where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaItem whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaItem whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
