/*
 * This file is generated by jOOQ.
 */
package org.a1cey.bookshelf_pro_plugins.db.jooq.tables;


import java.time.LocalDate;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.a1cey.bookshelf_pro_plugins.db.jooq.Keys;
import org.a1cey.bookshelf_pro_plugins.db.jooq.Public;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.MediaItem.MediaItemPath;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.MovieActor.MovieActorPath;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.MovieDirector.MovieDirectorPath;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.MovieStudio.MovieStudioPath;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records.MovieRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Movie extends TableImpl<MovieRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.movie</code>
     */
    public static final Movie MOVIE = new Movie();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MovieRecord> getRecordType() {
        return MovieRecord.class;
    }

    /**
     * The column <code>public.movie.id</code>.
     */
    public final TableField<MovieRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.movie.imdb_title_id</code>.
     */
    public final TableField<MovieRecord, String> IMDB_TITLE_ID = createField(DSL.name("imdb_title_id"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.movie.duration</code>.
     */
    public final TableField<MovieRecord, Integer> DURATION = createField(DSL.name("duration"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.movie.release_date</code>.
     */
    public final TableField<MovieRecord, LocalDate> RELEASE_DATE = createField(DSL.name("release_date"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.movie.origin_country</code>.
     */
    public final TableField<MovieRecord, String> ORIGIN_COUNTRY = createField(DSL.name("origin_country"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private Movie(Name alias, Table<MovieRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Movie(Name alias, Table<MovieRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.movie</code> table reference
     */
    public Movie(String alias) {
        this(DSL.name(alias), MOVIE);
    }

    /**
     * Create an aliased <code>public.movie</code> table reference
     */
    public Movie(Name alias) {
        this(alias, MOVIE);
    }

    /**
     * Create a <code>public.movie</code> table reference
     */
    public Movie() {
        this(DSL.name("movie"), null);
    }

    public <O extends Record> Movie(Table<O> path, ForeignKey<O, MovieRecord> childPath, InverseForeignKey<O, MovieRecord> parentPath) {
        super(path, childPath, parentPath, MOVIE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class MoviePath extends Movie implements Path<MovieRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MoviePath(Table<O> path, ForeignKey<O, MovieRecord> childPath, InverseForeignKey<O, MovieRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MoviePath(Name alias, Table<MovieRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MoviePath as(String alias) {
            return new MoviePath(DSL.name(alias), this);
        }

        @Override
        public MoviePath as(Name alias) {
            return new MoviePath(alias, this);
        }

        @Override
        public MoviePath as(Table<?> alias) {
            return new MoviePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<MovieRecord> getPrimaryKey() {
        return Keys.MOVIE_PKEY;
    }

    @Override
    public List<UniqueKey<MovieRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.MOVIE_IMDB_TITLE_ID_KEY);
    }

    @Override
    public List<ForeignKey<MovieRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MOVIE__MOVIE_ID_FKEY);
    }

    private transient MediaItemPath _mediaItem;

    /**
     * Get the implicit join path to the <code>public.media_item</code> table.
     */
    public MediaItemPath mediaItem() {
        if (_mediaItem == null)
            _mediaItem = new MediaItemPath(this, Keys.MOVIE__MOVIE_ID_FKEY, null);

        return _mediaItem;
    }

    private transient MovieActorPath _movieActor;

    /**
     * Get the implicit to-many join path to the <code>public.movie_actor</code>
     * table
     */
    public MovieActorPath movieActor() {
        if (_movieActor == null)
            _movieActor = new MovieActorPath(this, null, Keys.MOVIE_ACTOR__MOVIE_ACTOR_MOVIE_ID_FKEY.getInverseKey());

        return _movieActor;
    }

    private transient MovieDirectorPath _movieDirector;

    /**
     * Get the implicit to-many join path to the
     * <code>public.movie_director</code> table
     */
    public MovieDirectorPath movieDirector() {
        if (_movieDirector == null)
            _movieDirector = new MovieDirectorPath(this, null, Keys.MOVIE_DIRECTOR__MOVIE_DIRECTOR_MOVIE_ID_FKEY.getInverseKey());

        return _movieDirector;
    }

    private transient MovieStudioPath _movieStudio;

    /**
     * Get the implicit to-many join path to the
     * <code>public.movie_studio</code> table
     */
    public MovieStudioPath movieStudio() {
        if (_movieStudio == null)
            _movieStudio = new MovieStudioPath(this, null, Keys.MOVIE_STUDIO__MOVIE_STUDIO_MOVIE_ID_FKEY.getInverseKey());

        return _movieStudio;
    }

    @Override
    public Movie as(String alias) {
        return new Movie(DSL.name(alias), this);
    }

    @Override
    public Movie as(Name alias) {
        return new Movie(alias, this);
    }

    @Override
    public Movie as(Table<?> alias) {
        return new Movie(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Movie rename(String name) {
        return new Movie(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Movie rename(Name name) {
        return new Movie(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Movie rename(Table<?> name) {
        return new Movie(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Movie where(Condition condition) {
        return new Movie(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Movie where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Movie where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Movie where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Movie where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Movie where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Movie where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Movie where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Movie whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Movie whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
