/*
 * This file is generated by jOOQ.
 */
package org.a1cey.bookshelf_pro_plugins.db.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.a1cey.bookshelf_pro_plugins.db.jooq.Keys;
import org.a1cey.bookshelf_pro_plugins.db.jooq.Public;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.Movie.MoviePath;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records.MovieStudioRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MovieStudio extends TableImpl<MovieStudioRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.movie_studio</code>
     */
    public static final MovieStudio MOVIE_STUDIO = new MovieStudio();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MovieStudioRecord> getRecordType() {
        return MovieStudioRecord.class;
    }

    /**
     * The column <code>public.movie_studio.movie_id</code>.
     */
    public final TableField<MovieStudioRecord, UUID> MOVIE_ID = createField(DSL.name("movie_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.movie_studio.name</code>.
     */
    public final TableField<MovieStudioRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private MovieStudio(Name alias, Table<MovieStudioRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MovieStudio(Name alias, Table<MovieStudioRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.movie_studio</code> table reference
     */
    public MovieStudio(String alias) {
        this(DSL.name(alias), MOVIE_STUDIO);
    }

    /**
     * Create an aliased <code>public.movie_studio</code> table reference
     */
    public MovieStudio(Name alias) {
        this(alias, MOVIE_STUDIO);
    }

    /**
     * Create a <code>public.movie_studio</code> table reference
     */
    public MovieStudio() {
        this(DSL.name("movie_studio"), null);
    }

    public <O extends Record> MovieStudio(Table<O> path, ForeignKey<O, MovieStudioRecord> childPath, InverseForeignKey<O, MovieStudioRecord> parentPath) {
        super(path, childPath, parentPath, MOVIE_STUDIO);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class MovieStudioPath extends MovieStudio implements Path<MovieStudioRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MovieStudioPath(Table<O> path, ForeignKey<O, MovieStudioRecord> childPath, InverseForeignKey<O, MovieStudioRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MovieStudioPath(Name alias, Table<MovieStudioRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MovieStudioPath as(String alias) {
            return new MovieStudioPath(DSL.name(alias), this);
        }

        @Override
        public MovieStudioPath as(Name alias) {
            return new MovieStudioPath(alias, this);
        }

        @Override
        public MovieStudioPath as(Table<?> alias) {
            return new MovieStudioPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<MovieStudioRecord> getPrimaryKey() {
        return Keys.MOVIE_STUDIO_PKEY;
    }

    @Override
    public List<ForeignKey<MovieStudioRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MOVIE_STUDIO__MOVIE_STUDIO_MOVIE_ID_FKEY);
    }

    private transient MoviePath _movie;

    /**
     * Get the implicit join path to the <code>public.movie</code> table.
     */
    public MoviePath movie() {
        if (_movie == null)
            _movie = new MoviePath(this, Keys.MOVIE_STUDIO__MOVIE_STUDIO_MOVIE_ID_FKEY, null);

        return _movie;
    }

    @Override
    public MovieStudio as(String alias) {
        return new MovieStudio(DSL.name(alias), this);
    }

    @Override
    public MovieStudio as(Name alias) {
        return new MovieStudio(alias, this);
    }

    @Override
    public MovieStudio as(Table<?> alias) {
        return new MovieStudio(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MovieStudio rename(String name) {
        return new MovieStudio(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MovieStudio rename(Name name) {
        return new MovieStudio(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MovieStudio rename(Table<?> name) {
        return new MovieStudio(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MovieStudio where(Condition condition) {
        return new MovieStudio(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MovieStudio where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MovieStudio where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MovieStudio where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MovieStudio where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MovieStudio where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MovieStudio where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MovieStudio where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MovieStudio whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MovieStudio whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
