/*
 * This file is generated by jOOQ.
 */
package org.a1cey.bookshelf_pro_plugins.db.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.a1cey.bookshelf_pro_plugins.db.jooq.Keys;
import org.a1cey.bookshelf_pro_plugins.db.jooq.Public;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.Movie.MoviePath;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records.MovieActorRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MovieActor extends TableImpl<MovieActorRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.movie_actor</code>
     */
    public static final MovieActor MOVIE_ACTOR = new MovieActor();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MovieActorRecord> getRecordType() {
        return MovieActorRecord.class;
    }

    /**
     * The column <code>public.movie_actor.movie_id</code>.
     */
    public final TableField<MovieActorRecord, UUID> MOVIE_ID = createField(DSL.name("movie_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.movie_actor.name</code>.
     */
    public final TableField<MovieActorRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.movie_actor.role</code>.
     */
    public final TableField<MovieActorRecord, String> ROLE = createField(DSL.name("role"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private MovieActor(Name alias, Table<MovieActorRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MovieActor(Name alias, Table<MovieActorRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.movie_actor</code> table reference
     */
    public MovieActor(String alias) {
        this(DSL.name(alias), MOVIE_ACTOR);
    }

    /**
     * Create an aliased <code>public.movie_actor</code> table reference
     */
    public MovieActor(Name alias) {
        this(alias, MOVIE_ACTOR);
    }

    /**
     * Create a <code>public.movie_actor</code> table reference
     */
    public MovieActor() {
        this(DSL.name("movie_actor"), null);
    }

    public <O extends Record> MovieActor(Table<O> path, ForeignKey<O, MovieActorRecord> childPath, InverseForeignKey<O, MovieActorRecord> parentPath) {
        super(path, childPath, parentPath, MOVIE_ACTOR);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class MovieActorPath extends MovieActor implements Path<MovieActorRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MovieActorPath(Table<O> path, ForeignKey<O, MovieActorRecord> childPath, InverseForeignKey<O, MovieActorRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MovieActorPath(Name alias, Table<MovieActorRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MovieActorPath as(String alias) {
            return new MovieActorPath(DSL.name(alias), this);
        }

        @Override
        public MovieActorPath as(Name alias) {
            return new MovieActorPath(alias, this);
        }

        @Override
        public MovieActorPath as(Table<?> alias) {
            return new MovieActorPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<MovieActorRecord> getPrimaryKey() {
        return Keys.MOVIE_ACTOR_PKEY;
    }

    @Override
    public List<ForeignKey<MovieActorRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MOVIE_ACTOR__MOVIE_ACTOR_MOVIE_ID_FKEY);
    }

    private transient MoviePath _movie;

    /**
     * Get the implicit join path to the <code>public.movie</code> table.
     */
    public MoviePath movie() {
        if (_movie == null)
            _movie = new MoviePath(this, Keys.MOVIE_ACTOR__MOVIE_ACTOR_MOVIE_ID_FKEY, null);

        return _movie;
    }

    @Override
    public MovieActor as(String alias) {
        return new MovieActor(DSL.name(alias), this);
    }

    @Override
    public MovieActor as(Name alias) {
        return new MovieActor(alias, this);
    }

    @Override
    public MovieActor as(Table<?> alias) {
        return new MovieActor(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MovieActor rename(String name) {
        return new MovieActor(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MovieActor rename(Name name) {
        return new MovieActor(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MovieActor rename(Table<?> name) {
        return new MovieActor(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MovieActor where(Condition condition) {
        return new MovieActor(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MovieActor where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MovieActor where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MovieActor where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MovieActor where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MovieActor where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MovieActor where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MovieActor where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MovieActor whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MovieActor whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
