/*
 * This file is generated by jOOQ.
 */
package org.a1cey.bookshelf_pro_plugins.db.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.a1cey.bookshelf_pro_plugins.db.jooq.Keys;
import org.a1cey.bookshelf_pro_plugins.db.jooq.Public;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.Account.AccountPath;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.MediaItem.MediaItemPath;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.ReviewChange.ReviewChangePath;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records.ReviewRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Review extends TableImpl<ReviewRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.review</code>
     */
    public static final Review REVIEW = new Review();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReviewRecord> getRecordType() {
        return ReviewRecord.class;
    }

    /**
     * The column <code>public.review.id</code>.
     */
    public final TableField<ReviewRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.review.media_item_id</code>.
     */
    public final TableField<ReviewRecord, UUID> MEDIA_ITEM_ID = createField(DSL.name("media_item_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.review.owner</code>.
     */
    public final TableField<ReviewRecord, UUID> OWNER = createField(DSL.name("owner"), SQLDataType.UUID.nullable(false), this, "");

    private Review(Name alias, Table<ReviewRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Review(Name alias, Table<ReviewRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.review</code> table reference
     */
    public Review(String alias) {
        this(DSL.name(alias), REVIEW);
    }

    /**
     * Create an aliased <code>public.review</code> table reference
     */
    public Review(Name alias) {
        this(alias, REVIEW);
    }

    /**
     * Create a <code>public.review</code> table reference
     */
    public Review() {
        this(DSL.name("review"), null);
    }

    public <O extends Record> Review(Table<O> path, ForeignKey<O, ReviewRecord> childPath, InverseForeignKey<O, ReviewRecord> parentPath) {
        super(path, childPath, parentPath, REVIEW);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ReviewPath extends Review implements Path<ReviewRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ReviewPath(Table<O> path, ForeignKey<O, ReviewRecord> childPath, InverseForeignKey<O, ReviewRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ReviewPath(Name alias, Table<ReviewRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ReviewPath as(String alias) {
            return new ReviewPath(DSL.name(alias), this);
        }

        @Override
        public ReviewPath as(Name alias) {
            return new ReviewPath(alias, this);
        }

        @Override
        public ReviewPath as(Table<?> alias) {
            return new ReviewPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<ReviewRecord> getPrimaryKey() {
        return Keys.REVIEW_PKEY;
    }

    @Override
    public List<UniqueKey<ReviewRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.REVIEW_OWNER_MEDIA_ITEM_ID_KEY);
    }

    @Override
    public List<ForeignKey<ReviewRecord, ?>> getReferences() {
        return Arrays.asList(Keys.REVIEW__REVIEW_MEDIA_ITEM_ID_FKEY, Keys.REVIEW__REVIEW_OWNER_FKEY);
    }

    private transient MediaItemPath _mediaItem;

    /**
     * Get the implicit join path to the <code>public.media_item</code> table.
     */
    public MediaItemPath mediaItem() {
        if (_mediaItem == null)
            _mediaItem = new MediaItemPath(this, Keys.REVIEW__REVIEW_MEDIA_ITEM_ID_FKEY, null);

        return _mediaItem;
    }

    private transient AccountPath _account;

    /**
     * Get the implicit join path to the <code>public.account</code> table.
     */
    public AccountPath account() {
        if (_account == null)
            _account = new AccountPath(this, Keys.REVIEW__REVIEW_OWNER_FKEY, null);

        return _account;
    }

    private transient ReviewChangePath _reviewChange;

    /**
     * Get the implicit to-many join path to the
     * <code>public.review_change</code> table
     */
    public ReviewChangePath reviewChange() {
        if (_reviewChange == null)
            _reviewChange = new ReviewChangePath(this, null, Keys.REVIEW_CHANGE__REVIEW_CHANGE_REVIEW_ID_FKEY.getInverseKey());

        return _reviewChange;
    }

    @Override
    public Review as(String alias) {
        return new Review(DSL.name(alias), this);
    }

    @Override
    public Review as(Name alias) {
        return new Review(alias, this);
    }

    @Override
    public Review as(Table<?> alias) {
        return new Review(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Review rename(String name) {
        return new Review(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Review rename(Name name) {
        return new Review(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Review rename(Table<?> name) {
        return new Review(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Review where(Condition condition) {
        return new Review(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Review where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Review where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Review where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Review where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Review where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Review where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Review where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Review whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Review whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
