/*
 * This file is generated by jOOQ.
 */
package org.a1cey.bookshelf_pro_plugins.db.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.a1cey.bookshelf_pro_plugins.db.jooq.Keys;
import org.a1cey.bookshelf_pro_plugins.db.jooq.Public;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.ConsumptionProgressSnapshot.ConsumptionProgressSnapshotPath;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.Review.ReviewPath;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records.ReviewChangeRecord;
import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReviewChange extends TableImpl<ReviewChangeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.review_change</code>
     */
    public static final ReviewChange REVIEW_CHANGE = new ReviewChange();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReviewChangeRecord> getRecordType() {
        return ReviewChangeRecord.class;
    }

    /**
     * The column <code>public.review_change.review_id</code>.
     */
    public final TableField<ReviewChangeRecord, UUID> REVIEW_ID = createField(DSL.name("review_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.review_change.rating</code>.
     */
    public final TableField<ReviewChangeRecord, Double> RATING = createField(DSL.name("rating"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.review_change.comment</code>.
     */
    public final TableField<ReviewChangeRecord, String> COMMENT = createField(DSL.name("comment"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.review_change.review_date</code>.
     */
    public final TableField<ReviewChangeRecord, LocalDateTime> REVIEW_DATE = createField(DSL.name("review_date"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column
     * <code>public.review_change.consumption_progress_snapshot_consumption_progress_id</code>.
     */
    public final TableField<ReviewChangeRecord, UUID> CONSUMPTION_PROGRESS_SNAPSHOT_CONSUMPTION_PROGRESS_ID = createField(DSL.name("consumption_progress_snapshot_consumption_progress_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column
     * <code>public.review_change.consumption_progress_snapshot_created_at</code>.
     */
    public final TableField<ReviewChangeRecord, LocalDateTime> CONSUMPTION_PROGRESS_SNAPSHOT_CREATED_AT = createField(DSL.name("consumption_progress_snapshot_created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    private ReviewChange(Name alias, Table<ReviewChangeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ReviewChange(Name alias, Table<ReviewChangeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.review_change</code> table reference
     */
    public ReviewChange(String alias) {
        this(DSL.name(alias), REVIEW_CHANGE);
    }

    /**
     * Create an aliased <code>public.review_change</code> table reference
     */
    public ReviewChange(Name alias) {
        this(alias, REVIEW_CHANGE);
    }

    /**
     * Create a <code>public.review_change</code> table reference
     */
    public ReviewChange() {
        this(DSL.name("review_change"), null);
    }

    public <O extends Record> ReviewChange(Table<O> path, ForeignKey<O, ReviewChangeRecord> childPath, InverseForeignKey<O, ReviewChangeRecord> parentPath) {
        super(path, childPath, parentPath, REVIEW_CHANGE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ReviewChangePath extends ReviewChange implements Path<ReviewChangeRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ReviewChangePath(Table<O> path, ForeignKey<O, ReviewChangeRecord> childPath, InverseForeignKey<O, ReviewChangeRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ReviewChangePath(Name alias, Table<ReviewChangeRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ReviewChangePath as(String alias) {
            return new ReviewChangePath(DSL.name(alias), this);
        }

        @Override
        public ReviewChangePath as(Name alias) {
            return new ReviewChangePath(alias, this);
        }

        @Override
        public ReviewChangePath as(Table<?> alias) {
            return new ReviewChangePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<ReviewChangeRecord> getPrimaryKey() {
        return Keys.REVIEW_CHANGE_PKEY;
    }

    @Override
    public List<ForeignKey<ReviewChangeRecord, ?>> getReferences() {
        return Arrays.asList(Keys.REVIEW_CHANGE__REVIEW_CHANGE_CONSUMPTION_PROGRESS_SNAPSHOT_FKEY, Keys.REVIEW_CHANGE__REVIEW_CHANGE_REVIEW_ID_FKEY);
    }

    private transient ConsumptionProgressSnapshotPath _consumptionProgressSnapshot;

    /**
     * Get the implicit join path to the
     * <code>public.consumption_progress_snapshot</code> table.
     */
    public ConsumptionProgressSnapshotPath consumptionProgressSnapshot() {
        if (_consumptionProgressSnapshot == null)
            _consumptionProgressSnapshot = new ConsumptionProgressSnapshotPath(this, Keys.REVIEW_CHANGE__REVIEW_CHANGE_CONSUMPTION_PROGRESS_SNAPSHOT_FKEY, null);

        return _consumptionProgressSnapshot;
    }

    private transient ReviewPath _review;

    /**
     * Get the implicit join path to the <code>public.review</code> table.
     */
    public ReviewPath review() {
        if (_review == null)
            _review = new ReviewPath(this, Keys.REVIEW_CHANGE__REVIEW_CHANGE_REVIEW_ID_FKEY, null);

        return _review;
    }

    @Override
    public List<Check<ReviewChangeRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("review_change_rating_check"), "(((rating >= (0.0)::double precision) AND (rating <= (10.0)::double precision)))", true)
        );
    }

    @Override
    public ReviewChange as(String alias) {
        return new ReviewChange(DSL.name(alias), this);
    }

    @Override
    public ReviewChange as(Name alias) {
        return new ReviewChange(alias, this);
    }

    @Override
    public ReviewChange as(Table<?> alias) {
        return new ReviewChange(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReviewChange rename(String name) {
        return new ReviewChange(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReviewChange rename(Name name) {
        return new ReviewChange(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReviewChange rename(Table<?> name) {
        return new ReviewChange(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReviewChange where(Condition condition) {
        return new ReviewChange(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReviewChange where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReviewChange where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReviewChange where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReviewChange where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReviewChange where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReviewChange where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReviewChange where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReviewChange whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReviewChange whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
