/*
 * This file is generated by jOOQ.
 */
package org.a1cey.bookshelf_pro_plugins.db.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.a1cey.bookshelf_pro_plugins.db.jooq.Keys;
import org.a1cey.bookshelf_pro_plugins.db.jooq.Public;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.BookshelfEntry.BookshelfEntryPath;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.Watchlists.WatchlistsPath;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records.WatchlistItemsRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WatchlistItems extends TableImpl<WatchlistItemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.watchlist_items</code>
     */
    public static final WatchlistItems WATCHLIST_ITEMS = new WatchlistItems();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WatchlistItemsRecord> getRecordType() {
        return WatchlistItemsRecord.class;
    }

    /**
     * The column <code>public.watchlist_items.watchlist_id</code>.
     */
    public final TableField<WatchlistItemsRecord, UUID> WATCHLIST_ID = createField(DSL.name("watchlist_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.watchlist_items.bookshelf_entry_id</code>.
     */
    public final TableField<WatchlistItemsRecord, UUID> BOOKSHELF_ENTRY_ID = createField(DSL.name("bookshelf_entry_id"), SQLDataType.UUID.nullable(false), this, "");

    private WatchlistItems(Name alias, Table<WatchlistItemsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private WatchlistItems(Name alias, Table<WatchlistItemsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.watchlist_items</code> table reference
     */
    public WatchlistItems(String alias) {
        this(DSL.name(alias), WATCHLIST_ITEMS);
    }

    /**
     * Create an aliased <code>public.watchlist_items</code> table reference
     */
    public WatchlistItems(Name alias) {
        this(alias, WATCHLIST_ITEMS);
    }

    /**
     * Create a <code>public.watchlist_items</code> table reference
     */
    public WatchlistItems() {
        this(DSL.name("watchlist_items"), null);
    }

    public <O extends Record> WatchlistItems(Table<O> path, ForeignKey<O, WatchlistItemsRecord> childPath, InverseForeignKey<O, WatchlistItemsRecord> parentPath) {
        super(path, childPath, parentPath, WATCHLIST_ITEMS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class WatchlistItemsPath extends WatchlistItems implements Path<WatchlistItemsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> WatchlistItemsPath(Table<O> path, ForeignKey<O, WatchlistItemsRecord> childPath, InverseForeignKey<O, WatchlistItemsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private WatchlistItemsPath(Name alias, Table<WatchlistItemsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public WatchlistItemsPath as(String alias) {
            return new WatchlistItemsPath(DSL.name(alias), this);
        }

        @Override
        public WatchlistItemsPath as(Name alias) {
            return new WatchlistItemsPath(alias, this);
        }

        @Override
        public WatchlistItemsPath as(Table<?> alias) {
            return new WatchlistItemsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<WatchlistItemsRecord> getPrimaryKey() {
        return Keys.WATCHLIST_ITEMS_PKEY;
    }

    @Override
    public List<ForeignKey<WatchlistItemsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.WATCHLIST_ITEMS__WATCHLIST_ITEMS_BOOKSHELF_ENTRY_ID_FKEY, Keys.WATCHLIST_ITEMS__WATCHLIST_ITEMS_WATCHLIST_ID_FKEY);
    }

    private transient BookshelfEntryPath _bookshelfEntry;

    /**
     * Get the implicit join path to the <code>public.bookshelf_entry</code>
     * table.
     */
    public BookshelfEntryPath bookshelfEntry() {
        if (_bookshelfEntry == null)
            _bookshelfEntry = new BookshelfEntryPath(this, Keys.WATCHLIST_ITEMS__WATCHLIST_ITEMS_BOOKSHELF_ENTRY_ID_FKEY, null);

        return _bookshelfEntry;
    }

    private transient WatchlistsPath _watchlists;

    /**
     * Get the implicit join path to the <code>public.watchlists</code> table.
     */
    public WatchlistsPath watchlists() {
        if (_watchlists == null)
            _watchlists = new WatchlistsPath(this, Keys.WATCHLIST_ITEMS__WATCHLIST_ITEMS_WATCHLIST_ID_FKEY, null);

        return _watchlists;
    }

    @Override
    public WatchlistItems as(String alias) {
        return new WatchlistItems(DSL.name(alias), this);
    }

    @Override
    public WatchlistItems as(Name alias) {
        return new WatchlistItems(alias, this);
    }

    @Override
    public WatchlistItems as(Table<?> alias) {
        return new WatchlistItems(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public WatchlistItems rename(String name) {
        return new WatchlistItems(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WatchlistItems rename(Name name) {
        return new WatchlistItems(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public WatchlistItems rename(Table<?> name) {
        return new WatchlistItems(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WatchlistItems where(Condition condition) {
        return new WatchlistItems(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WatchlistItems where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WatchlistItems where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WatchlistItems where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WatchlistItems where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WatchlistItems where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WatchlistItems where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WatchlistItems where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WatchlistItems whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WatchlistItems whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
