/*
 * This file is generated by jOOQ.
 */
package org.a1cey.bookshelf_pro_plugins.db.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.a1cey.bookshelf_pro_plugins.db.jooq.Keys;
import org.a1cey.bookshelf_pro_plugins.db.jooq.Public;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.Account.AccountPath;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.BookshelfEntry.BookshelfEntryPath;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.WatchlistItems.WatchlistItemsPath;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records.WatchlistsRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Watchlists extends TableImpl<WatchlistsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.watchlists</code>
     */
    public static final Watchlists WATCHLISTS = new Watchlists();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WatchlistsRecord> getRecordType() {
        return WatchlistsRecord.class;
    }

    /**
     * The column <code>public.watchlists.id</code>.
     */
    public final TableField<WatchlistsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.watchlists.owner</code>.
     */
    public final TableField<WatchlistsRecord, UUID> OWNER = createField(DSL.name("owner"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.watchlists.title</code>.
     */
    public final TableField<WatchlistsRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private Watchlists(Name alias, Table<WatchlistsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Watchlists(Name alias, Table<WatchlistsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.watchlists</code> table reference
     */
    public Watchlists(String alias) {
        this(DSL.name(alias), WATCHLISTS);
    }

    /**
     * Create an aliased <code>public.watchlists</code> table reference
     */
    public Watchlists(Name alias) {
        this(alias, WATCHLISTS);
    }

    /**
     * Create a <code>public.watchlists</code> table reference
     */
    public Watchlists() {
        this(DSL.name("watchlists"), null);
    }

    public <O extends Record> Watchlists(Table<O> path, ForeignKey<O, WatchlistsRecord> childPath, InverseForeignKey<O, WatchlistsRecord> parentPath) {
        super(path, childPath, parentPath, WATCHLISTS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class WatchlistsPath extends Watchlists implements Path<WatchlistsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> WatchlistsPath(Table<O> path, ForeignKey<O, WatchlistsRecord> childPath, InverseForeignKey<O, WatchlistsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private WatchlistsPath(Name alias, Table<WatchlistsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public WatchlistsPath as(String alias) {
            return new WatchlistsPath(DSL.name(alias), this);
        }

        @Override
        public WatchlistsPath as(Name alias) {
            return new WatchlistsPath(alias, this);
        }

        @Override
        public WatchlistsPath as(Table<?> alias) {
            return new WatchlistsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<WatchlistsRecord> getPrimaryKey() {
        return Keys.WATCHLISTS_PKEY;
    }

    @Override
    public List<ForeignKey<WatchlistsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.WATCHLISTS__WATCHLISTS_OWNER_FKEY);
    }

    private transient AccountPath _account;

    /**
     * Get the implicit join path to the <code>public.account</code> table.
     */
    public AccountPath account() {
        if (_account == null)
            _account = new AccountPath(this, Keys.WATCHLISTS__WATCHLISTS_OWNER_FKEY, null);

        return _account;
    }

    private transient WatchlistItemsPath _watchlistItems;

    /**
     * Get the implicit to-many join path to the
     * <code>public.watchlist_items</code> table
     */
    public WatchlistItemsPath watchlistItems() {
        if (_watchlistItems == null)
            _watchlistItems = new WatchlistItemsPath(this, null, Keys.WATCHLIST_ITEMS__WATCHLIST_ITEMS_WATCHLIST_ID_FKEY.getInverseKey());

        return _watchlistItems;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.bookshelf_entry</code> table
     */
    public BookshelfEntryPath bookshelfEntry() {
        return watchlistItems().bookshelfEntry();
    }

    @Override
    public Watchlists as(String alias) {
        return new Watchlists(DSL.name(alias), this);
    }

    @Override
    public Watchlists as(Name alias) {
        return new Watchlists(alias, this);
    }

    @Override
    public Watchlists as(Table<?> alias) {
        return new Watchlists(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Watchlists rename(String name) {
        return new Watchlists(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Watchlists rename(Name name) {
        return new Watchlists(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Watchlists rename(Table<?> name) {
        return new Watchlists(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Watchlists where(Condition condition) {
        return new Watchlists(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Watchlists where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Watchlists where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Watchlists where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Watchlists where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Watchlists where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Watchlists where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Watchlists where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Watchlists whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Watchlists whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
