/*
 * This file is generated by jOOQ.
 */
package org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records;


import java.util.UUID;

import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.BookAuthor;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BookAuthorRecord extends UpdatableRecordImpl<BookAuthorRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.book_author.book_id</code>.
     */
    public void setBookId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.book_author.book_id</code>.
     */
    public UUID getBookId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.book_author.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.book_author.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookAuthorRecord
     */
    public BookAuthorRecord() {
        super(BookAuthor.BOOK_AUTHOR);
    }

    /**
     * Create a detached, initialised BookAuthorRecord
     */
    public BookAuthorRecord(UUID bookId, String name) {
        super(BookAuthor.BOOK_AUTHOR);

        setBookId(bookId);
        setName(name);
        resetChangedOnNotNull();
    }
}
