/*
 * This file is generated by jOOQ.
 */
package org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records;


import java.time.LocalDate;
import java.util.UUID;

import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.Book;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BookRecord extends UpdatableRecordImpl<BookRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.book.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.book.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.book.isbn</code>.
     */
    public void setIsbn(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.book.isbn</code>.
     */
    public String getIsbn() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.book.page_count</code>.
     */
    public void setPageCount(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.book.page_count</code>.
     */
    public Integer getPageCount() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.book.publish_date</code>.
     */
    public void setPublishDate(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.book.publish_date</code>.
     */
    public LocalDate getPublishDate() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>public.book.publisher</code>.
     */
    public void setPublisher(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.book.publisher</code>.
     */
    public String getPublisher() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.book.publish_place</code>.
     */
    public void setPublishPlace(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.book.publish_place</code>.
     */
    public String getPublishPlace() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookRecord
     */
    public BookRecord() {
        super(Book.BOOK);
    }

    /**
     * Create a detached, initialised BookRecord
     */
    public BookRecord(UUID id, String isbn, Integer pageCount, LocalDate publishDate, String publisher, String publishPlace) {
        super(Book.BOOK);

        setId(id);
        setIsbn(isbn);
        setPageCount(pageCount);
        setPublishDate(publishDate);
        setPublisher(publisher);
        setPublishPlace(publishPlace);
        resetChangedOnNotNull();
    }
}
