/*
 * This file is generated by jOOQ.
 */
package org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records;


import java.util.UUID;

import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.BookshelfEntryLabel;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BookshelfEntryLabelRecord extends UpdatableRecordImpl<BookshelfEntryLabelRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.bookshelf_entry_label.bookshelf_entry_id</code>.
     */
    public void setBookshelfEntryId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.bookshelf_entry_label.bookshelf_entry_id</code>.
     */
    public UUID getBookshelfEntryId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.bookshelf_entry_label.label</code>.
     */
    public void setLabel(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.bookshelf_entry_label.label</code>.
     */
    public String getLabel() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookshelfEntryLabelRecord
     */
    public BookshelfEntryLabelRecord() {
        super(BookshelfEntryLabel.BOOKSHELF_ENTRY_LABEL);
    }

    /**
     * Create a detached, initialised BookshelfEntryLabelRecord
     */
    public BookshelfEntryLabelRecord(UUID bookshelfEntryId, String label) {
        super(BookshelfEntryLabel.BOOKSHELF_ENTRY_LABEL);

        setBookshelfEntryId(bookshelfEntryId);
        setLabel(label);
        resetChangedOnNotNull();
    }
}
