/*
 * This file is generated by jOOQ.
 */
package org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records;


import java.time.LocalDateTime;
import java.util.UUID;

import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.ConsumptionProgressSnapshot;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ConsumptionProgressSnapshotRecord extends UpdatableRecordImpl<ConsumptionProgressSnapshotRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.consumption_progress_snapshot.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.consumption_progress_snapshot.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for
     * <code>public.consumption_progress_snapshot.consumption_state</code>.
     */
    public void setConsumptionState(String value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>public.consumption_progress_snapshot.consumption_state</code>.
     */
    public String getConsumptionState() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.consumption_progress_snapshot.type</code>.
     */
    public void setType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.consumption_progress_snapshot.type</code>.
     */
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.consumption_progress_snapshot.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.consumption_progress_snapshot.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for
     * <code>public.consumption_progress_snapshot.current_page</code>.
     */
    public void setCurrentPage(Integer value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>public.consumption_progress_snapshot.current_page</code>.
     */
    public Integer getCurrentPage() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.consumption_progress_snapshot.total_pages</code>.
     */
    public void setTotalPages(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.consumption_progress_snapshot.total_pages</code>.
     */
    public Integer getTotalPages() {
        return (Integer) get(5);
    }

    /**
     * Setter for
     * <code>public.consumption_progress_snapshot.current_duration_seconds</code>.
     */
    public void setCurrentDurationSeconds(Integer value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>public.consumption_progress_snapshot.current_duration_seconds</code>.
     */
    public Integer getCurrentDurationSeconds() {
        return (Integer) get(6);
    }

    /**
     * Setter for
     * <code>public.consumption_progress_snapshot.total_duration_seconds</code>.
     */
    public void setTotalDurationSeconds(Integer value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>public.consumption_progress_snapshot.total_duration_seconds</code>.
     */
    public Integer getTotalDurationSeconds() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ConsumptionProgressSnapshotRecord
     */
    public ConsumptionProgressSnapshotRecord() {
        super(ConsumptionProgressSnapshot.CONSUMPTION_PROGRESS_SNAPSHOT);
    }

    /**
     * Create a detached, initialised ConsumptionProgressSnapshotRecord
     */
    public ConsumptionProgressSnapshotRecord(UUID id, String consumptionState, String type, LocalDateTime createdAt, Integer currentPage, Integer totalPages, Integer currentDurationSeconds, Integer totalDurationSeconds) {
        super(ConsumptionProgressSnapshot.CONSUMPTION_PROGRESS_SNAPSHOT);

        setId(id);
        setConsumptionState(consumptionState);
        setType(type);
        setCreatedAt(createdAt);
        setCurrentPage(currentPage);
        setTotalPages(totalPages);
        setCurrentDurationSeconds(currentDurationSeconds);
        setTotalDurationSeconds(totalDurationSeconds);
        resetChangedOnNotNull();
    }
}
