/*
 * This file is generated by jOOQ.
 */
package org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records;


import java.util.UUID;

import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.ConsumptionProgress;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ConsumptionProgressRecord extends UpdatableRecordImpl<ConsumptionProgressRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.consumption_progress.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.consumption_progress.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.consumption_progress.bookshelf_entry_id</code>.
     */
    public void setBookshelfEntryId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.consumption_progress.bookshelf_entry_id</code>.
     */
    public UUID getBookshelfEntryId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.consumption_progress.state</code>.
     */
    public void setState(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.consumption_progress.state</code>.
     */
    public String getState() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.consumption_progress.type</code>.
     */
    public void setType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.consumption_progress.type</code>.
     */
    public String getType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.consumption_progress.current_page</code>.
     */
    public void setCurrentPage(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.consumption_progress.current_page</code>.
     */
    public Integer getCurrentPage() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.consumption_progress.total_pages</code>.
     */
    public void setTotalPages(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.consumption_progress.total_pages</code>.
     */
    public Integer getTotalPages() {
        return (Integer) get(5);
    }

    /**
     * Setter for
     * <code>public.consumption_progress.current_duration_seconds</code>.
     */
    public void setCurrentDurationSeconds(Integer value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>public.consumption_progress.current_duration_seconds</code>.
     */
    public Integer getCurrentDurationSeconds() {
        return (Integer) get(6);
    }

    /**
     * Setter for
     * <code>public.consumption_progress.total_duration_seconds</code>.
     */
    public void setTotalDurationSeconds(Integer value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>public.consumption_progress.total_duration_seconds</code>.
     */
    public Integer getTotalDurationSeconds() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ConsumptionProgressRecord
     */
    public ConsumptionProgressRecord() {
        super(ConsumptionProgress.CONSUMPTION_PROGRESS);
    }

    /**
     * Create a detached, initialised ConsumptionProgressRecord
     */
    public ConsumptionProgressRecord(UUID id, UUID bookshelfEntryId, String state, String type, Integer currentPage, Integer totalPages, Integer currentDurationSeconds, Integer totalDurationSeconds) {
        super(ConsumptionProgress.CONSUMPTION_PROGRESS);

        setId(id);
        setBookshelfEntryId(bookshelfEntryId);
        setState(state);
        setType(type);
        setCurrentPage(currentPage);
        setTotalPages(totalPages);
        setCurrentDurationSeconds(currentDurationSeconds);
        setTotalDurationSeconds(totalDurationSeconds);
        resetChangedOnNotNull();
    }
}
