/*
 * This file is generated by jOOQ.
 */
package org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records;


import java.util.UUID;

import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.MediaItem;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MediaItemRecord extends UpdatableRecordImpl<MediaItemRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.media_item.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.media_item.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.media_item.type</code>.
     */
    public void setType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.media_item.type</code>.
     */
    public String getType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.media_item.title</code>.
     */
    public void setTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.media_item.title</code>.
     */
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.media_item.subtitle</code>.
     */
    public void setSubtitle(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.media_item.subtitle</code>.
     */
    public String getSubtitle() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.media_item.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.media_item.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.media_item.cover_image_url</code>.
     */
    public void setCoverImageUrl(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.media_item.cover_image_url</code>.
     */
    public String getCoverImageUrl() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.media_item.owner_id</code>.
     */
    public void setOwnerId(UUID value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.media_item.owner_id</code>.
     */
    public UUID getOwnerId() {
        return (UUID) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MediaItemRecord
     */
    public MediaItemRecord() {
        super(MediaItem.MEDIA_ITEM);
    }

    /**
     * Create a detached, initialised MediaItemRecord
     */
    public MediaItemRecord(UUID id, String type, String title, String subtitle, String description, String coverImageUrl, UUID ownerId) {
        super(MediaItem.MEDIA_ITEM);

        setId(id);
        setType(type);
        setTitle(title);
        setSubtitle(subtitle);
        setDescription(description);
        setCoverImageUrl(coverImageUrl);
        setOwnerId(ownerId);
        resetChangedOnNotNull();
    }
}
