/*
 * This file is generated by jOOQ.
 */
package org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records;


import java.util.UUID;

import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.MediaItemLanguage;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MediaItemLanguageRecord extends UpdatableRecordImpl<MediaItemLanguageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.media_item_language.media_item_id</code>.
     */
    public void setMediaItemId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.media_item_language.media_item_id</code>.
     */
    public UUID getMediaItemId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.media_item_language.iso_code</code>.
     */
    public void setIsoCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.media_item_language.iso_code</code>.
     */
    public String getIsoCode() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MediaItemLanguageRecord
     */
    public MediaItemLanguageRecord() {
        super(MediaItemLanguage.MEDIA_ITEM_LANGUAGE);
    }

    /**
     * Create a detached, initialised MediaItemLanguageRecord
     */
    public MediaItemLanguageRecord(UUID mediaItemId, String isoCode) {
        super(MediaItemLanguage.MEDIA_ITEM_LANGUAGE);

        setMediaItemId(mediaItemId);
        setIsoCode(isoCode);
        resetChangedOnNotNull();
    }
}
