/*
 * This file is generated by jOOQ.
 */
package org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records;


import java.util.UUID;

import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.MovieStudio;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MovieStudioRecord extends UpdatableRecordImpl<MovieStudioRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.movie_studio.movie_id</code>.
     */
    public void setMovieId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.movie_studio.movie_id</code>.
     */
    public UUID getMovieId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.movie_studio.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.movie_studio.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MovieStudioRecord
     */
    public MovieStudioRecord() {
        super(MovieStudio.MOVIE_STUDIO);
    }

    /**
     * Create a detached, initialised MovieStudioRecord
     */
    public MovieStudioRecord(UUID movieId, String name) {
        super(MovieStudio.MOVIE_STUDIO);

        setMovieId(movieId);
        setName(name);
        resetChangedOnNotNull();
    }
}
