/*
 * This file is generated by jOOQ.
 */
package org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records;


import java.time.LocalDate;
import java.util.UUID;

import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.Movie;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MovieRecord extends UpdatableRecordImpl<MovieRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.movie.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.movie.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.movie.imdb_title_id</code>.
     */
    public void setImdbTitleId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.movie.imdb_title_id</code>.
     */
    public String getImdbTitleId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.movie.duration</code>.
     */
    public void setDuration(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.movie.duration</code>.
     */
    public Integer getDuration() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.movie.release_date</code>.
     */
    public void setReleaseDate(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.movie.release_date</code>.
     */
    public LocalDate getReleaseDate() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>public.movie.origin_country</code>.
     */
    public void setOriginCountry(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.movie.origin_country</code>.
     */
    public String getOriginCountry() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MovieRecord
     */
    public MovieRecord() {
        super(Movie.MOVIE);
    }

    /**
     * Create a detached, initialised MovieRecord
     */
    public MovieRecord(UUID id, String imdbTitleId, Integer duration, LocalDate releaseDate, String originCountry) {
        super(Movie.MOVIE);

        setId(id);
        setImdbTitleId(imdbTitleId);
        setDuration(duration);
        setReleaseDate(releaseDate);
        setOriginCountry(originCountry);
        resetChangedOnNotNull();
    }
}
