/*
 * This file is generated by jOOQ.
 */
package org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records;


import java.util.UUID;

import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.MovieActor;
import org.jooq.Record3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MovieActorRecord extends UpdatableRecordImpl<MovieActorRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.movie_actor.movie_id</code>.
     */
    public void setMovieId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.movie_actor.movie_id</code>.
     */
    public UUID getMovieId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.movie_actor.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.movie_actor.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.movie_actor.role</code>.
     */
    public void setRole(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.movie_actor.role</code>.
     */
    public String getRole() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<UUID, String, String> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MovieActorRecord
     */
    public MovieActorRecord() {
        super(MovieActor.MOVIE_ACTOR);
    }

    /**
     * Create a detached, initialised MovieActorRecord
     */
    public MovieActorRecord(UUID movieId, String name, String role) {
        super(MovieActor.MOVIE_ACTOR);

        setMovieId(movieId);
        setName(name);
        setRole(role);
        resetChangedOnNotNull();
    }
}
