/*
 * This file is generated by jOOQ.
 */
package org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records;


import java.util.UUID;

import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.PlaylistItems;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PlaylistItemsRecord extends UpdatableRecordImpl<PlaylistItemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.playlist_items.playlist_id</code>.
     */
    public void setPlaylistId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.playlist_items.playlist_id</code>.
     */
    public UUID getPlaylistId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.playlist_items.bookshelf_entry_id</code>.
     */
    public void setBookshelfEntryId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.playlist_items.bookshelf_entry_id</code>.
     */
    public UUID getBookshelfEntryId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.playlist_items.position</code>.
     */
    public void setPosition(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.playlist_items.position</code>.
     */
    public Integer getPosition() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlaylistItemsRecord
     */
    public PlaylistItemsRecord() {
        super(PlaylistItems.PLAYLIST_ITEMS);
    }

    /**
     * Create a detached, initialised PlaylistItemsRecord
     */
    public PlaylistItemsRecord(UUID playlistId, UUID bookshelfEntryId, Integer position) {
        super(PlaylistItems.PLAYLIST_ITEMS);

        setPlaylistId(playlistId);
        setBookshelfEntryId(bookshelfEntryId);
        setPosition(position);
        resetChangedOnNotNull();
    }
}
