/*
 * This file is generated by jOOQ.
 */
package org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records;


import java.util.UUID;

import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.Review;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReviewRecord extends UpdatableRecordImpl<ReviewRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.review.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.review.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.review.media_item_id</code>.
     */
    public void setMediaItemId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.review.media_item_id</code>.
     */
    public UUID getMediaItemId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.review.owner</code>.
     */
    public void setOwner(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.review.owner</code>.
     */
    public UUID getOwner() {
        return (UUID) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReviewRecord
     */
    public ReviewRecord() {
        super(Review.REVIEW);
    }

    /**
     * Create a detached, initialised ReviewRecord
     */
    public ReviewRecord(UUID id, UUID mediaItemId, UUID owner) {
        super(Review.REVIEW);

        setId(id);
        setMediaItemId(mediaItemId);
        setOwner(owner);
        resetChangedOnNotNull();
    }
}
