/*
 * This file is generated by jOOQ.
 */
package org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records;


import java.time.LocalDateTime;
import java.util.UUID;

import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.ReviewChange;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReviewChangeRecord extends UpdatableRecordImpl<ReviewChangeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.review_change.review_id</code>.
     */
    public void setReviewId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.review_change.review_id</code>.
     */
    public UUID getReviewId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.review_change.rating</code>.
     */
    public void setRating(Double value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.review_change.rating</code>.
     */
    public Double getRating() {
        return (Double) get(1);
    }

    /**
     * Setter for <code>public.review_change.comment</code>.
     */
    public void setComment(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.review_change.comment</code>.
     */
    public String getComment() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.review_change.review_date</code>.
     */
    public void setReviewDate(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.review_change.review_date</code>.
     */
    public LocalDateTime getReviewDate() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for
     * <code>public.review_change.consumption_progress_snapshot_consumption_progress_id</code>.
     */
    public void setConsumptionProgressSnapshotConsumptionProgressId(UUID value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>public.review_change.consumption_progress_snapshot_consumption_progress_id</code>.
     */
    public UUID getConsumptionProgressSnapshotConsumptionProgressId() {
        return (UUID) get(4);
    }

    /**
     * Setter for
     * <code>public.review_change.consumption_progress_snapshot_created_at</code>.
     */
    public void setConsumptionProgressSnapshotCreatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>public.review_change.consumption_progress_snapshot_created_at</code>.
     */
    public LocalDateTime getConsumptionProgressSnapshotCreatedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, LocalDateTime> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReviewChangeRecord
     */
    public ReviewChangeRecord() {
        super(ReviewChange.REVIEW_CHANGE);
    }

    /**
     * Create a detached, initialised ReviewChangeRecord
     */
    public ReviewChangeRecord(UUID reviewId, Double rating, String comment, LocalDateTime reviewDate, UUID consumptionProgressSnapshotConsumptionProgressId, LocalDateTime consumptionProgressSnapshotCreatedAt) {
        super(ReviewChange.REVIEW_CHANGE);

        setReviewId(reviewId);
        setRating(rating);
        setComment(comment);
        setReviewDate(reviewDate);
        setConsumptionProgressSnapshotConsumptionProgressId(consumptionProgressSnapshotConsumptionProgressId);
        setConsumptionProgressSnapshotCreatedAt(consumptionProgressSnapshotCreatedAt);
        resetChangedOnNotNull();
    }
}
