/*
 * This file is generated by jOOQ.
 */
package org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records;


import java.util.UUID;

import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.Watchlists;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WatchlistsRecord extends UpdatableRecordImpl<WatchlistsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.watchlists.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.watchlists.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.watchlists.owner</code>.
     */
    public void setOwner(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.watchlists.owner</code>.
     */
    public UUID getOwner() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.watchlists.title</code>.
     */
    public void setTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.watchlists.title</code>.
     */
    public String getTitle() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WatchlistsRecord
     */
    public WatchlistsRecord() {
        super(Watchlists.WATCHLISTS);
    }

    /**
     * Create a detached, initialised WatchlistsRecord
     */
    public WatchlistsRecord(UUID id, UUID owner, String title) {
        super(Watchlists.WATCHLISTS);

        setId(id);
        setOwner(owner);
        setTitle(title);
        resetChangedOnNotNull();
    }
}
