/*
 * This file is generated by jOOQ.
 */
package org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records;


import java.util.UUID;

import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.WatchlistItems;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WatchlistItemsRecord extends UpdatableRecordImpl<WatchlistItemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.watchlist_items.watchlist_id</code>.
     */
    public void setWatchlistId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.watchlist_items.watchlist_id</code>.
     */
    public UUID getWatchlistId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.watchlist_items.bookshelf_entry_id</code>.
     */
    public void setBookshelfEntryId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.watchlist_items.bookshelf_entry_id</code>.
     */
    public UUID getBookshelfEntryId() {
        return (UUID) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WatchlistItemsRecord
     */
    public WatchlistItemsRecord() {
        super(WatchlistItems.WATCHLIST_ITEMS);
    }

    /**
     * Create a detached, initialised WatchlistItemsRecord
     */
    public WatchlistItemsRecord(UUID watchlistId, UUID bookshelfEntryId) {
        super(WatchlistItems.WATCHLIST_ITEMS);

        setWatchlistId(watchlistId);
        setBookshelfEntryId(bookshelfEntryId);
        resetChangedOnNotNull();
    }
}
