/*
 * This file is generated by jOOQ.
 */
package org.a1cey.bookshelf_pro_plugins.db.jooq;


import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.Account;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.Book;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.BookAuthor;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.MediaItem;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.MediaItemLanguage;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records.AccountRecord;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records.BookAuthorRecord;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records.BookRecord;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records.MediaItemLanguageRecord;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records.MediaItemRecord;
import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AccountRecord> ACCOUNT_PKEY = Internal.createUniqueKey(Account.ACCOUNT, DSL.name("account_pkey"), new TableField[] { Account.ACCOUNT.ID }, true);
    public static final UniqueKey<AccountRecord> ACCOUNT_USERNAME_KEY = Internal.createUniqueKey(Account.ACCOUNT, DSL.name("account_username_key"), new TableField[] { Account.ACCOUNT.USERNAME }, true);
    public static final UniqueKey<BookRecord> BOOK_PKEY = Internal.createUniqueKey(Book.BOOK, DSL.name("book_pkey"), new TableField[] { Book.BOOK.ID }, true);
    public static final UniqueKey<BookAuthorRecord> BOOK_AUTHOR_PKEY = Internal.createUniqueKey(BookAuthor.BOOK_AUTHOR, DSL.name("book_author_pkey"), new TableField[] { BookAuthor.BOOK_AUTHOR.BOOK_ID, BookAuthor.BOOK_AUTHOR.NAME }, true);
    public static final UniqueKey<MediaItemRecord> MEDIA_ITEM_PKEY = Internal.createUniqueKey(MediaItem.MEDIA_ITEM, DSL.name("media_item_pkey"), new TableField[] { MediaItem.MEDIA_ITEM.ID }, true);
    public static final UniqueKey<MediaItemLanguageRecord> MEDIA_ITEM_LANGUAGE_PKEY = Internal.createUniqueKey(MediaItemLanguage.MEDIA_ITEM_LANGUAGE, DSL.name("media_item_language_pkey"), new TableField[] { MediaItemLanguage.MEDIA_ITEM_LANGUAGE.MEDIA_ITEM_ID, MediaItemLanguage.MEDIA_ITEM_LANGUAGE.ISO_CODE }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<BookRecord, MediaItemRecord> BOOK__BOOK_ID_FKEY = Internal.createForeignKey(Book.BOOK, DSL.name("book_id_fkey"), new TableField[] { Book.BOOK.ID }, Keys.MEDIA_ITEM_PKEY, new TableField[] { MediaItem.MEDIA_ITEM.ID }, true);
    public static final ForeignKey<BookAuthorRecord, BookRecord> BOOK_AUTHOR__BOOK_AUTHOR_BOOK_ID_FKEY = Internal.createForeignKey(BookAuthor.BOOK_AUTHOR, DSL.name("book_author_book_id_fkey"), new TableField[] { BookAuthor.BOOK_AUTHOR.BOOK_ID }, Keys.BOOK_PKEY, new TableField[] { Book.BOOK.ID }, true);
    public static final ForeignKey<MediaItemRecord, AccountRecord> MEDIA_ITEM__MEDIA_ITEM_OWNER_ID_FKEY = Internal.createForeignKey(MediaItem.MEDIA_ITEM, DSL.name("media_item_owner_id_fkey"), new TableField[] { MediaItem.MEDIA_ITEM.OWNER_ID }, Keys.ACCOUNT_PKEY, new TableField[] { Account.ACCOUNT.ID }, true);
    public static final ForeignKey<MediaItemLanguageRecord, MediaItemRecord> MEDIA_ITEM_LANGUAGE__MEDIA_ITEM_LANGUAGE_MEDIA_ITEM_ID_FKEY = Internal.createForeignKey(MediaItemLanguage.MEDIA_ITEM_LANGUAGE, DSL.name("media_item_language_media_item_id_fkey"), new TableField[] { MediaItemLanguage.MEDIA_ITEM_LANGUAGE.MEDIA_ITEM_ID }, Keys.MEDIA_ITEM_PKEY, new TableField[] { MediaItem.MEDIA_ITEM.ID }, true);
}
