/*
 * This file is generated by jOOQ.
 */
package org.a1cey.bookshelf_pro_plugins.db.jooq;


import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.Account;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.Book;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.BookAuthor;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.BookshelfEntry;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.BookshelfEntryLabel;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.ConsumptionProgress;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.ConsumptionProgressSnapshot;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.MediaItem;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.MediaItemLanguage;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.Movie;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.MovieActor;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.MovieDirector;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.MovieStudio;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.PlaylistItems;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.Playlists;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.Review;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.ReviewChange;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.WatchlistItems;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.Watchlists;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records.AccountRecord;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records.BookAuthorRecord;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records.BookRecord;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records.BookshelfEntryLabelRecord;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records.BookshelfEntryRecord;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records.ConsumptionProgressRecord;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records.ConsumptionProgressSnapshotRecord;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records.MediaItemLanguageRecord;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records.MediaItemRecord;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records.MovieActorRecord;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records.MovieDirectorRecord;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records.MovieRecord;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records.MovieStudioRecord;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records.PlaylistItemsRecord;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records.PlaylistsRecord;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records.ReviewChangeRecord;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records.ReviewRecord;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records.WatchlistItemsRecord;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.records.WatchlistsRecord;
import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AccountRecord> ACCOUNT_PKEY = Internal.createUniqueKey(Account.ACCOUNT, DSL.name("account_pkey"), new TableField[] { Account.ACCOUNT.ID }, true);
    public static final UniqueKey<AccountRecord> ACCOUNT_USERNAME_KEY = Internal.createUniqueKey(Account.ACCOUNT, DSL.name("account_username_key"), new TableField[] { Account.ACCOUNT.USERNAME }, true);
    public static final UniqueKey<BookRecord> BOOK_PKEY = Internal.createUniqueKey(Book.BOOK, DSL.name("book_pkey"), new TableField[] { Book.BOOK.ID }, true);
    public static final UniqueKey<BookAuthorRecord> BOOK_AUTHOR_PKEY = Internal.createUniqueKey(BookAuthor.BOOK_AUTHOR, DSL.name("book_author_pkey"), new TableField[] { BookAuthor.BOOK_AUTHOR.BOOK_ID, BookAuthor.BOOK_AUTHOR.NAME }, true);
    public static final UniqueKey<BookshelfEntryRecord> BOOKSHELF_ENTRY_OWNER_MEDIA_ITEM_ID_KEY = Internal.createUniqueKey(BookshelfEntry.BOOKSHELF_ENTRY, DSL.name("bookshelf_entry_owner_media_item_id_key"), new TableField[] { BookshelfEntry.BOOKSHELF_ENTRY.OWNER, BookshelfEntry.BOOKSHELF_ENTRY.MEDIA_ITEM_ID }, true);
    public static final UniqueKey<BookshelfEntryRecord> BOOKSHELF_ENTRY_PKEY = Internal.createUniqueKey(BookshelfEntry.BOOKSHELF_ENTRY, DSL.name("bookshelf_entry_pkey"), new TableField[] { BookshelfEntry.BOOKSHELF_ENTRY.ID }, true);
    public static final UniqueKey<BookshelfEntryLabelRecord> BOOKSHELF_ENTRY_LABEL_PKEY = Internal.createUniqueKey(BookshelfEntryLabel.BOOKSHELF_ENTRY_LABEL, DSL.name("bookshelf_entry_label_pkey"), new TableField[] { BookshelfEntryLabel.BOOKSHELF_ENTRY_LABEL.BOOKSHELF_ENTRY_ID, BookshelfEntryLabel.BOOKSHELF_ENTRY_LABEL.LABEL }, true);
    public static final UniqueKey<ConsumptionProgressRecord> CONSUMPTION_PROGRESS_PKEY = Internal.createUniqueKey(ConsumptionProgress.CONSUMPTION_PROGRESS, DSL.name("consumption_progress_pkey"), new TableField[] { ConsumptionProgress.CONSUMPTION_PROGRESS.ID }, true);
    public static final UniqueKey<ConsumptionProgressSnapshotRecord> CONSUMPTION_PROGRESS_SNAPSHOT_PKEY = Internal.createUniqueKey(ConsumptionProgressSnapshot.CONSUMPTION_PROGRESS_SNAPSHOT, DSL.name("consumption_progress_snapshot_pkey"), new TableField[] { ConsumptionProgressSnapshot.CONSUMPTION_PROGRESS_SNAPSHOT.CONSUMPTION_PROGRESS_ID, ConsumptionProgressSnapshot.CONSUMPTION_PROGRESS_SNAPSHOT.CREATED_AT }, true);
    public static final UniqueKey<MediaItemRecord> MEDIA_ITEM_PKEY = Internal.createUniqueKey(MediaItem.MEDIA_ITEM, DSL.name("media_item_pkey"), new TableField[] { MediaItem.MEDIA_ITEM.ID }, true);
    public static final UniqueKey<MediaItemLanguageRecord> MEDIA_ITEM_LANGUAGE_PKEY = Internal.createUniqueKey(MediaItemLanguage.MEDIA_ITEM_LANGUAGE, DSL.name("media_item_language_pkey"), new TableField[] { MediaItemLanguage.MEDIA_ITEM_LANGUAGE.MEDIA_ITEM_ID, MediaItemLanguage.MEDIA_ITEM_LANGUAGE.ISO_CODE }, true);
    public static final UniqueKey<MovieRecord> MOVIE_IMDB_TITLE_ID_KEY = Internal.createUniqueKey(Movie.MOVIE, DSL.name("movie_imdb_title_id_key"), new TableField[] { Movie.MOVIE.IMDB_TITLE_ID }, true);
    public static final UniqueKey<MovieRecord> MOVIE_PKEY = Internal.createUniqueKey(Movie.MOVIE, DSL.name("movie_pkey"), new TableField[] { Movie.MOVIE.ID }, true);
    public static final UniqueKey<MovieActorRecord> MOVIE_ACTOR_PKEY = Internal.createUniqueKey(MovieActor.MOVIE_ACTOR, DSL.name("movie_actor_pkey"), new TableField[] { MovieActor.MOVIE_ACTOR.MOVIE_ID, MovieActor.MOVIE_ACTOR.NAME, MovieActor.MOVIE_ACTOR.ROLE }, true);
    public static final UniqueKey<MovieDirectorRecord> MOVIE_DIRECTOR_PKEY = Internal.createUniqueKey(MovieDirector.MOVIE_DIRECTOR, DSL.name("movie_director_pkey"), new TableField[] { MovieDirector.MOVIE_DIRECTOR.MOVIE_ID, MovieDirector.MOVIE_DIRECTOR.NAME }, true);
    public static final UniqueKey<MovieStudioRecord> MOVIE_STUDIO_PKEY = Internal.createUniqueKey(MovieStudio.MOVIE_STUDIO, DSL.name("movie_studio_pkey"), new TableField[] { MovieStudio.MOVIE_STUDIO.MOVIE_ID, MovieStudio.MOVIE_STUDIO.NAME }, true);
    public static final UniqueKey<PlaylistItemsRecord> PLAYLIST_ITEMS_PKEY = Internal.createUniqueKey(PlaylistItems.PLAYLIST_ITEMS, DSL.name("playlist_items_pkey"), new TableField[] { PlaylistItems.PLAYLIST_ITEMS.PLAYLIST_ID, PlaylistItems.PLAYLIST_ITEMS.BOOKSHELF_ENTRY_ID }, true);
    public static final UniqueKey<PlaylistItemsRecord> PLAYLIST_ITEMS_POSITION_PLAYLIST_ID_KEY = Internal.createUniqueKey(PlaylistItems.PLAYLIST_ITEMS, DSL.name("playlist_items_position_playlist_id_key"), new TableField[] { PlaylistItems.PLAYLIST_ITEMS.POSITION, PlaylistItems.PLAYLIST_ITEMS.PLAYLIST_ID }, true);
    public static final UniqueKey<PlaylistsRecord> PLAYLISTS_PKEY = Internal.createUniqueKey(Playlists.PLAYLISTS, DSL.name("playlists_pkey"), new TableField[] { Playlists.PLAYLISTS.ID }, true);
    public static final UniqueKey<ReviewRecord> REVIEW_OWNER_MEDIA_ITEM_ID_KEY = Internal.createUniqueKey(Review.REVIEW, DSL.name("review_owner_media_item_id_key"), new TableField[] { Review.REVIEW.OWNER, Review.REVIEW.MEDIA_ITEM_ID }, true);
    public static final UniqueKey<ReviewRecord> REVIEW_PKEY = Internal.createUniqueKey(Review.REVIEW, DSL.name("review_pkey"), new TableField[] { Review.REVIEW.ID }, true);
    public static final UniqueKey<ReviewChangeRecord> REVIEW_CHANGE_PKEY = Internal.createUniqueKey(ReviewChange.REVIEW_CHANGE, DSL.name("review_change_pkey"), new TableField[] { ReviewChange.REVIEW_CHANGE.REVIEW_ID, ReviewChange.REVIEW_CHANGE.REVIEW_DATE }, true);
    public static final UniqueKey<WatchlistItemsRecord> WATCHLIST_ITEMS_PKEY = Internal.createUniqueKey(WatchlistItems.WATCHLIST_ITEMS, DSL.name("watchlist_items_pkey"), new TableField[] { WatchlistItems.WATCHLIST_ITEMS.WATCHLIST_ID, WatchlistItems.WATCHLIST_ITEMS.BOOKSHELF_ENTRY_ID }, true);
    public static final UniqueKey<WatchlistsRecord> WATCHLISTS_PKEY = Internal.createUniqueKey(Watchlists.WATCHLISTS, DSL.name("watchlists_pkey"), new TableField[] { Watchlists.WATCHLISTS.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<BookRecord, MediaItemRecord> BOOK__BOOK_ID_FKEY = Internal.createForeignKey(Book.BOOK, DSL.name("book_id_fkey"), new TableField[] { Book.BOOK.ID }, Keys.MEDIA_ITEM_PKEY, new TableField[] { MediaItem.MEDIA_ITEM.ID }, true);
    public static final ForeignKey<BookAuthorRecord, BookRecord> BOOK_AUTHOR__BOOK_AUTHOR_BOOK_ID_FKEY = Internal.createForeignKey(BookAuthor.BOOK_AUTHOR, DSL.name("book_author_book_id_fkey"), new TableField[] { BookAuthor.BOOK_AUTHOR.BOOK_ID }, Keys.BOOK_PKEY, new TableField[] { Book.BOOK.ID }, true);
    public static final ForeignKey<BookshelfEntryRecord, MediaItemRecord> BOOKSHELF_ENTRY__BOOKSHELF_ENTRY_MEDIA_ITEM_ID_FKEY = Internal.createForeignKey(BookshelfEntry.BOOKSHELF_ENTRY, DSL.name("bookshelf_entry_media_item_id_fkey"), new TableField[] { BookshelfEntry.BOOKSHELF_ENTRY.MEDIA_ITEM_ID }, Keys.MEDIA_ITEM_PKEY, new TableField[] { MediaItem.MEDIA_ITEM.ID }, true);
    public static final ForeignKey<BookshelfEntryRecord, AccountRecord> BOOKSHELF_ENTRY__BOOKSHELF_ENTRY_OWNER_FKEY = Internal.createForeignKey(BookshelfEntry.BOOKSHELF_ENTRY, DSL.name("bookshelf_entry_owner_fkey"), new TableField[] { BookshelfEntry.BOOKSHELF_ENTRY.OWNER }, Keys.ACCOUNT_PKEY, new TableField[] { Account.ACCOUNT.ID }, true);
    public static final ForeignKey<BookshelfEntryLabelRecord, BookshelfEntryRecord> BOOKSHELF_ENTRY_LABEL__BOOKSHELF_ENTRY_LABEL_BOOKSHELF_ENTRY_ID_FKEY = Internal.createForeignKey(BookshelfEntryLabel.BOOKSHELF_ENTRY_LABEL, DSL.name("bookshelf_entry_label_bookshelf_entry_id_fkey"), new TableField[] { BookshelfEntryLabel.BOOKSHELF_ENTRY_LABEL.BOOKSHELF_ENTRY_ID }, Keys.BOOKSHELF_ENTRY_PKEY, new TableField[] { BookshelfEntry.BOOKSHELF_ENTRY.ID }, true);
    public static final ForeignKey<ConsumptionProgressRecord, BookshelfEntryRecord> CONSUMPTION_PROGRESS__CONSUMPTION_PROGRESS_BOOKSHELF_ENTRY_ID_FKEY = Internal.createForeignKey(ConsumptionProgress.CONSUMPTION_PROGRESS, DSL.name("consumption_progress_bookshelf_entry_id_fkey"), new TableField[] { ConsumptionProgress.CONSUMPTION_PROGRESS.BOOKSHELF_ENTRY_ID }, Keys.BOOKSHELF_ENTRY_PKEY, new TableField[] { BookshelfEntry.BOOKSHELF_ENTRY.ID }, true);
    public static final ForeignKey<ConsumptionProgressSnapshotRecord, ConsumptionProgressRecord> CONSUMPTION_PROGRESS_SNAPSHOT__CONSUMPTION_PROGRESS_SNAPSHOT_CONSUMPTION_PROGRESS_ID_FKEY = Internal.createForeignKey(ConsumptionProgressSnapshot.CONSUMPTION_PROGRESS_SNAPSHOT, DSL.name("consumption_progress_snapshot_consumption_progress_id_fkey"), new TableField[] { ConsumptionProgressSnapshot.CONSUMPTION_PROGRESS_SNAPSHOT.CONSUMPTION_PROGRESS_ID }, Keys.CONSUMPTION_PROGRESS_PKEY, new TableField[] { ConsumptionProgress.CONSUMPTION_PROGRESS.ID }, true);
    public static final ForeignKey<MediaItemRecord, AccountRecord> MEDIA_ITEM__MEDIA_ITEM_OWNER_ID_FKEY = Internal.createForeignKey(MediaItem.MEDIA_ITEM, DSL.name("media_item_owner_id_fkey"), new TableField[] { MediaItem.MEDIA_ITEM.OWNER_ID }, Keys.ACCOUNT_PKEY, new TableField[] { Account.ACCOUNT.ID }, true);
    public static final ForeignKey<MediaItemLanguageRecord, MediaItemRecord> MEDIA_ITEM_LANGUAGE__MEDIA_ITEM_LANGUAGE_MEDIA_ITEM_ID_FKEY = Internal.createForeignKey(MediaItemLanguage.MEDIA_ITEM_LANGUAGE, DSL.name("media_item_language_media_item_id_fkey"), new TableField[] { MediaItemLanguage.MEDIA_ITEM_LANGUAGE.MEDIA_ITEM_ID }, Keys.MEDIA_ITEM_PKEY, new TableField[] { MediaItem.MEDIA_ITEM.ID }, true);
    public static final ForeignKey<MovieRecord, MediaItemRecord> MOVIE__MOVIE_ID_FKEY = Internal.createForeignKey(Movie.MOVIE, DSL.name("movie_id_fkey"), new TableField[] { Movie.MOVIE.ID }, Keys.MEDIA_ITEM_PKEY, new TableField[] { MediaItem.MEDIA_ITEM.ID }, true);
    public static final ForeignKey<MovieActorRecord, MovieRecord> MOVIE_ACTOR__MOVIE_ACTOR_MOVIE_ID_FKEY = Internal.createForeignKey(MovieActor.MOVIE_ACTOR, DSL.name("movie_actor_movie_id_fkey"), new TableField[] { MovieActor.MOVIE_ACTOR.MOVIE_ID }, Keys.MOVIE_PKEY, new TableField[] { Movie.MOVIE.ID }, true);
    public static final ForeignKey<MovieDirectorRecord, MovieRecord> MOVIE_DIRECTOR__MOVIE_DIRECTOR_MOVIE_ID_FKEY = Internal.createForeignKey(MovieDirector.MOVIE_DIRECTOR, DSL.name("movie_director_movie_id_fkey"), new TableField[] { MovieDirector.MOVIE_DIRECTOR.MOVIE_ID }, Keys.MOVIE_PKEY, new TableField[] { Movie.MOVIE.ID }, true);
    public static final ForeignKey<MovieStudioRecord, MovieRecord> MOVIE_STUDIO__MOVIE_STUDIO_MOVIE_ID_FKEY = Internal.createForeignKey(MovieStudio.MOVIE_STUDIO, DSL.name("movie_studio_movie_id_fkey"), new TableField[] { MovieStudio.MOVIE_STUDIO.MOVIE_ID }, Keys.MOVIE_PKEY, new TableField[] { Movie.MOVIE.ID }, true);
    public static final ForeignKey<PlaylistItemsRecord, BookshelfEntryRecord> PLAYLIST_ITEMS__PLAYLIST_ITEMS_BOOKSHELF_ENTRY_ID_FKEY = Internal.createForeignKey(PlaylistItems.PLAYLIST_ITEMS, DSL.name("playlist_items_bookshelf_entry_id_fkey"), new TableField[] { PlaylistItems.PLAYLIST_ITEMS.BOOKSHELF_ENTRY_ID }, Keys.BOOKSHELF_ENTRY_PKEY, new TableField[] { BookshelfEntry.BOOKSHELF_ENTRY.ID }, true);
    public static final ForeignKey<PlaylistItemsRecord, PlaylistsRecord> PLAYLIST_ITEMS__PLAYLIST_ITEMS_PLAYLIST_ID_FKEY = Internal.createForeignKey(PlaylistItems.PLAYLIST_ITEMS, DSL.name("playlist_items_playlist_id_fkey"), new TableField[] { PlaylistItems.PLAYLIST_ITEMS.PLAYLIST_ID }, Keys.PLAYLISTS_PKEY, new TableField[] { Playlists.PLAYLISTS.ID }, true);
    public static final ForeignKey<PlaylistsRecord, AccountRecord> PLAYLISTS__PLAYLISTS_OWNER_FKEY = Internal.createForeignKey(Playlists.PLAYLISTS, DSL.name("playlists_owner_fkey"), new TableField[] { Playlists.PLAYLISTS.OWNER }, Keys.ACCOUNT_PKEY, new TableField[] { Account.ACCOUNT.ID }, true);
    public static final ForeignKey<ReviewRecord, MediaItemRecord> REVIEW__REVIEW_MEDIA_ITEM_ID_FKEY = Internal.createForeignKey(Review.REVIEW, DSL.name("review_media_item_id_fkey"), new TableField[] { Review.REVIEW.MEDIA_ITEM_ID }, Keys.MEDIA_ITEM_PKEY, new TableField[] { MediaItem.MEDIA_ITEM.ID }, true);
    public static final ForeignKey<ReviewRecord, AccountRecord> REVIEW__REVIEW_OWNER_FKEY = Internal.createForeignKey(Review.REVIEW, DSL.name("review_owner_fkey"), new TableField[] { Review.REVIEW.OWNER }, Keys.ACCOUNT_PKEY, new TableField[] { Account.ACCOUNT.ID }, true);
    public static final ForeignKey<ReviewChangeRecord, ConsumptionProgressSnapshotRecord> REVIEW_CHANGE__REVIEW_CHANGE_CONSUMPTION_PROGRESS_SNAPSHOT_FKEY = Internal.createForeignKey(ReviewChange.REVIEW_CHANGE, DSL.name("review_change_consumption_progress_snapshot_fkey"), new TableField[] { ReviewChange.REVIEW_CHANGE.CONSUMPTION_PROGRESS_SNAPSHOT_CONSUMPTION_PROGRESS_ID, ReviewChange.REVIEW_CHANGE.CONSUMPTION_PROGRESS_SNAPSHOT_CREATED_AT }, Keys.CONSUMPTION_PROGRESS_SNAPSHOT_PKEY, new TableField[] { ConsumptionProgressSnapshot.CONSUMPTION_PROGRESS_SNAPSHOT.CONSUMPTION_PROGRESS_ID, ConsumptionProgressSnapshot.CONSUMPTION_PROGRESS_SNAPSHOT.CREATED_AT }, true);
    public static final ForeignKey<ReviewChangeRecord, ReviewRecord> REVIEW_CHANGE__REVIEW_CHANGE_REVIEW_ID_FKEY = Internal.createForeignKey(ReviewChange.REVIEW_CHANGE, DSL.name("review_change_review_id_fkey"), new TableField[] { ReviewChange.REVIEW_CHANGE.REVIEW_ID }, Keys.REVIEW_PKEY, new TableField[] { Review.REVIEW.ID }, true);
    public static final ForeignKey<WatchlistItemsRecord, BookshelfEntryRecord> WATCHLIST_ITEMS__WATCHLIST_ITEMS_BOOKSHELF_ENTRY_ID_FKEY = Internal.createForeignKey(WatchlistItems.WATCHLIST_ITEMS, DSL.name("watchlist_items_bookshelf_entry_id_fkey"), new TableField[] { WatchlistItems.WATCHLIST_ITEMS.BOOKSHELF_ENTRY_ID }, Keys.BOOKSHELF_ENTRY_PKEY, new TableField[] { BookshelfEntry.BOOKSHELF_ENTRY.ID }, true);
    public static final ForeignKey<WatchlistItemsRecord, WatchlistsRecord> WATCHLIST_ITEMS__WATCHLIST_ITEMS_WATCHLIST_ID_FKEY = Internal.createForeignKey(WatchlistItems.WATCHLIST_ITEMS, DSL.name("watchlist_items_watchlist_id_fkey"), new TableField[] { WatchlistItems.WATCHLIST_ITEMS.WATCHLIST_ID }, Keys.WATCHLISTS_PKEY, new TableField[] { Watchlists.WATCHLISTS.ID }, true);
    public static final ForeignKey<WatchlistsRecord, AccountRecord> WATCHLISTS__WATCHLISTS_OWNER_FKEY = Internal.createForeignKey(Watchlists.WATCHLISTS, DSL.name("watchlists_owner_fkey"), new TableField[] { Watchlists.WATCHLISTS.OWNER }, Keys.ACCOUNT_PKEY, new TableField[] { Account.ACCOUNT.ID }, true);
}
