/*
 * This file is generated by jOOQ.
 */
package org.a1cey.bookshelf_pro_plugins.db.jooq;


import java.util.Arrays;
import java.util.List;

import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.Account;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.Book;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.BookAuthor;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.BookshelfEntry;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.BookshelfEntryLabel;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.ConsumptionProgress;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.ConsumptionProgressSnapshot;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.MediaItem;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.MediaItemLanguage;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.PlaylistItems;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.Playlists;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.Review;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.ReviewChange;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.WatchlistItems;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.Watchlists;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.account</code>.
     */
    public final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>public.book</code>.
     */
    public final Book BOOK = Book.BOOK;

    /**
     * The table <code>public.book_author</code>.
     */
    public final BookAuthor BOOK_AUTHOR = BookAuthor.BOOK_AUTHOR;

    /**
     * The table <code>public.bookshelf_entry</code>.
     */
    public final BookshelfEntry BOOKSHELF_ENTRY = BookshelfEntry.BOOKSHELF_ENTRY;

    /**
     * The table <code>public.bookshelf_entry_label</code>.
     */
    public final BookshelfEntryLabel BOOKSHELF_ENTRY_LABEL = BookshelfEntryLabel.BOOKSHELF_ENTRY_LABEL;

    /**
     * The table <code>public.consumption_progress</code>.
     */
    public final ConsumptionProgress CONSUMPTION_PROGRESS = ConsumptionProgress.CONSUMPTION_PROGRESS;

    /**
     * The table <code>public.consumption_progress_snapshot</code>.
     */
    public final ConsumptionProgressSnapshot CONSUMPTION_PROGRESS_SNAPSHOT = ConsumptionProgressSnapshot.CONSUMPTION_PROGRESS_SNAPSHOT;

    /**
     * The table <code>public.media_item</code>.
     */
    public final MediaItem MEDIA_ITEM = MediaItem.MEDIA_ITEM;

    /**
     * The table <code>public.media_item_language</code>.
     */
    public final MediaItemLanguage MEDIA_ITEM_LANGUAGE = MediaItemLanguage.MEDIA_ITEM_LANGUAGE;

    /**
     * The table <code>public.playlist_items</code>.
     */
    public final PlaylistItems PLAYLIST_ITEMS = PlaylistItems.PLAYLIST_ITEMS;

    /**
     * The table <code>public.playlists</code>.
     */
    public final Playlists PLAYLISTS = Playlists.PLAYLISTS;

    /**
     * The table <code>public.review</code>.
     */
    public final Review REVIEW = Review.REVIEW;

    /**
     * The table <code>public.review_change</code>.
     */
    public final ReviewChange REVIEW_CHANGE = ReviewChange.REVIEW_CHANGE;

    /**
     * The table <code>public.watchlist_items</code>.
     */
    public final WatchlistItems WATCHLIST_ITEMS = WatchlistItems.WATCHLIST_ITEMS;

    /**
     * The table <code>public.watchlists</code>.
     */
    public final Watchlists WATCHLISTS = Watchlists.WATCHLISTS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Account.ACCOUNT,
            Book.BOOK,
            BookAuthor.BOOK_AUTHOR,
            BookshelfEntry.BOOKSHELF_ENTRY,
            BookshelfEntryLabel.BOOKSHELF_ENTRY_LABEL,
            ConsumptionProgress.CONSUMPTION_PROGRESS,
            ConsumptionProgressSnapshot.CONSUMPTION_PROGRESS_SNAPSHOT,
            MediaItem.MEDIA_ITEM,
            MediaItemLanguage.MEDIA_ITEM_LANGUAGE,
            PlaylistItems.PLAYLIST_ITEMS,
            Playlists.PLAYLISTS,
            Review.REVIEW,
            ReviewChange.REVIEW_CHANGE,
            WatchlistItems.WATCHLIST_ITEMS,
            Watchlists.WATCHLISTS
        );
    }
}
