/*
 * This file is generated by jOOQ.
 */
package org.a1cey.bookshelf_pro_plugins.db.jooq;


import java.util.Arrays;
import java.util.List;

import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.Account;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.Book;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.BookAuthor;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.MediaItem;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.MediaItemLanguage;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.account</code>.
     */
    public final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>public.book</code>.
     */
    public final Book BOOK = Book.BOOK;

    /**
     * The table <code>public.book_author</code>.
     */
    public final BookAuthor BOOK_AUTHOR = BookAuthor.BOOK_AUTHOR;

    /**
     * The table <code>public.media_item</code>.
     */
    public final MediaItem MEDIA_ITEM = MediaItem.MEDIA_ITEM;

    /**
     * The table <code>public.media_item_language</code>.
     */
    public final MediaItemLanguage MEDIA_ITEM_LANGUAGE = MediaItemLanguage.MEDIA_ITEM_LANGUAGE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Account.ACCOUNT,
            Book.BOOK,
            BookAuthor.BOOK_AUTHOR,
            MediaItem.MEDIA_ITEM,
            MediaItemLanguage.MEDIA_ITEM_LANGUAGE
        );
    }
}
