/*
 * This file is generated by jOOQ.
 */
package org.a1cey.bookshelf_pro_plugins.db.jooq;


import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.Account;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.Book;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.BookAuthor;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.BookshelfEntry;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.BookshelfEntryLabel;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.ConsumptionProgress;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.ConsumptionProgressSnapshot;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.MediaItem;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.MediaItemLanguage;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.Movie;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.MovieActor;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.MovieDirector;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.MovieStudio;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.PlaylistItems;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.Playlists;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.Review;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.ReviewChange;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.WatchlistItems;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.Watchlists;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.account</code>.
     */
    public static final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>public.book</code>.
     */
    public static final Book BOOK = Book.BOOK;

    /**
     * The table <code>public.book_author</code>.
     */
    public static final BookAuthor BOOK_AUTHOR = BookAuthor.BOOK_AUTHOR;

    /**
     * The table <code>public.bookshelf_entry</code>.
     */
    public static final BookshelfEntry BOOKSHELF_ENTRY = BookshelfEntry.BOOKSHELF_ENTRY;

    /**
     * The table <code>public.bookshelf_entry_label</code>.
     */
    public static final BookshelfEntryLabel BOOKSHELF_ENTRY_LABEL = BookshelfEntryLabel.BOOKSHELF_ENTRY_LABEL;

    /**
     * The table <code>public.consumption_progress</code>.
     */
    public static final ConsumptionProgress CONSUMPTION_PROGRESS = ConsumptionProgress.CONSUMPTION_PROGRESS;

    /**
     * The table <code>public.consumption_progress_snapshot</code>.
     */
    public static final ConsumptionProgressSnapshot CONSUMPTION_PROGRESS_SNAPSHOT = ConsumptionProgressSnapshot.CONSUMPTION_PROGRESS_SNAPSHOT;

    /**
     * The table <code>public.media_item</code>.
     */
    public static final MediaItem MEDIA_ITEM = MediaItem.MEDIA_ITEM;

    /**
     * The table <code>public.media_item_language</code>.
     */
    public static final MediaItemLanguage MEDIA_ITEM_LANGUAGE = MediaItemLanguage.MEDIA_ITEM_LANGUAGE;

    /**
     * The table <code>public.movie</code>.
     */
    public static final Movie MOVIE = Movie.MOVIE;

    /**
     * The table <code>public.movie_actor</code>.
     */
    public static final MovieActor MOVIE_ACTOR = MovieActor.MOVIE_ACTOR;

    /**
     * The table <code>public.movie_director</code>.
     */
    public static final MovieDirector MOVIE_DIRECTOR = MovieDirector.MOVIE_DIRECTOR;

    /**
     * The table <code>public.movie_studio</code>.
     */
    public static final MovieStudio MOVIE_STUDIO = MovieStudio.MOVIE_STUDIO;

    /**
     * The table <code>public.playlist_items</code>.
     */
    public static final PlaylistItems PLAYLIST_ITEMS = PlaylistItems.PLAYLIST_ITEMS;

    /**
     * The table <code>public.playlists</code>.
     */
    public static final Playlists PLAYLISTS = Playlists.PLAYLISTS;

    /**
     * The table <code>public.review</code>.
     */
    public static final Review REVIEW = Review.REVIEW;

    /**
     * The table <code>public.review_change</code>.
     */
    public static final ReviewChange REVIEW_CHANGE = ReviewChange.REVIEW_CHANGE;

    /**
     * The table <code>public.watchlist_items</code>.
     */
    public static final WatchlistItems WATCHLIST_ITEMS = WatchlistItems.WATCHLIST_ITEMS;

    /**
     * The table <code>public.watchlists</code>.
     */
    public static final Watchlists WATCHLISTS = Watchlists.WATCHLISTS;
}
