/*
 * This file is generated by jOOQ.
 */
package org.a1cey.bookshelf_pro_plugins.db.jooq;


import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.Account;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.Book;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.BookAuthor;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.MediaItem;
import org.a1cey.bookshelf_pro_plugins.db.jooq.tables.MediaItemLanguage;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.account</code>.
     */
    public static final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>public.book</code>.
     */
    public static final Book BOOK = Book.BOOK;

    /**
     * The table <code>public.book_author</code>.
     */
    public static final BookAuthor BOOK_AUTHOR = BookAuthor.BOOK_AUTHOR;

    /**
     * The table <code>public.media_item</code>.
     */
    public static final MediaItem MEDIA_ITEM = MediaItem.MEDIA_ITEM;

    /**
     * The table <code>public.media_item_language</code>.
     */
    public static final MediaItemLanguage MEDIA_ITEM_LANGUAGE = MediaItemLanguage.MEDIA_ITEM_LANGUAGE;
}
